global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Infarstuructre.Data;
global using Infarstuructre.ViewModel;
global using Microsoft.AspNetCore.Identity;
global using Infarstuructre.BL;
global using Domin.Entity;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.CodeAnalysis.CSharp.Syntax;
global using System.Resources;
global using Yara.Resource;
global using Microsoft.AspNetCore.Authentication.Cookies;
global using static Infarstuructre.BL.IIRolsInformation;
global using TaskStatus = Domin.Entity.TaskStatus;
global using MimeKit;
global using MailKit.Security;
global using MailKit.Net.Smtp;
global using LamarModa.Api.Auth;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Microsoft.IdentityModel.Tokens;
global using Microsoft.OpenApi.Models;
global using System.Text;
global using System.Text.Json;
global using Yara.Helpers;
