//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domin.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domin.Resource.ResourceData", typeof(ResourceData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the price per kilo within the customer’s category of less than 10 kilos so that the process can be completed successfully....!.
        /// </summary>
        public static string ClintPricePerkgUnder10 {
            get {
                return ResourceManager.GetString("ClintPricePerkgUnder10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please retype the password...!.
        /// </summary>
        public static string ComparePassword {
            get {
                return ResourceManager.GetString("ComparePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must match...!.
        /// </summary>
        public static string ComparePasswordcomferm {
            get {
                return ResourceManager.GetString("ComparePasswordcomferm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of characters entered must not exceed 100 characters...!.
        /// </summary>
        public static string MaxLength100 {
            get {
                return ResourceManager.GetString("MaxLength100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of characters entered must not exceed 20 characters...!.
        /// </summary>
        public static string MaxLength20 {
            get {
                return ResourceManager.GetString("MaxLength20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of characters entered must not exceed 2000 characters...!.
        /// </summary>
        public static string MaxLength2000 {
            get {
                return ResourceManager.GetString("MaxLength2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of characters entered must not exceed 25 characters...!.
        /// </summary>
        public static string MaxLength25 {
            get {
                return ResourceManager.GetString("MaxLength25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of characters entered must not exceed 300 characters...!.
        /// </summary>
        public static string MaxLength300 {
            get {
                return ResourceManager.GetString("MaxLength300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of characters entered must not exceed 500 characters...!.
        /// </summary>
        public static string MaxLength500 {
            get {
                return ResourceManager.GetString("MaxLength500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of characters entered must not be less than one character, and the # symbol can be used to indicate the same page....!.
        /// </summary>
        public static string MinLength1 {
            get {
                return ResourceManager.GetString("MinLength1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of characters entered must not be less than 3 characters....!.
        /// </summary>
        public static string MinLength3 {
            get {
                return ResourceManager.GetString("MinLength3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of characters entered must not be less than 5 characters....!.
        /// </summary>
        public static string MinLength5 {
            get {
                return ResourceManager.GetString("MinLength5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum number of characters for the password must be at least 5 characters.
        /// </summary>
        public static string MinLengthPassword5 {
            get {
                return ResourceManager.GetString("MinLengthPassword5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the password for the process to complete successfully...!.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter phone number...!.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include your email..!.
        /// </summary>
        public static string RegisterEmail {
            get {
                return ResourceManager.GetString("RegisterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered format must be the email format...!.
        /// </summary>
        public static string RegisterEmailError {
            get {
                return ResourceManager.GetString("RegisterEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email...!.
        /// </summary>
        public static string RegisterEmaillogin {
            get {
                return ResourceManager.GetString("RegisterEmaillogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include full name.....!.
        /// </summary>
        public static string RegisterName {
            get {
                return ResourceManager.GetString("RegisterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your user permission for the process to complete successfully..!.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter the user name...!.
        /// </summary>
        public static string userName {
            get {
                return ResourceManager.GetString("userName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the address for the process to complete successfully.
        /// </summary>
        public static string VlAddres {
            get {
                return ResourceManager.GetString("VlAddres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the company address for the process to complete successfully...!.
        /// </summary>
        public static string VlAddresCompany {
            get {
                return ResourceManager.GetString("VlAddresCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the exchange rate in the local currency on the black market for the process to complete successfully....!.
        /// </summary>
        public static string VlBlackMarketExchangeRate {
            get {
                return ResourceManager.GetString("VlBlackMarketExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VlBuilding.
        /// </summary>
        public static string VlBuilding {
            get {
                return ResourceManager.GetString("VlBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please inclode the Catch Receipt.
        /// </summary>
        public static string VlCatchReceiptNo {
            get {
                return ResourceManager.GetString("VlCatchReceiptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the customer&apos;s delivery price so that the process is completed successfully...!.
        /// </summary>
        public static string VlClintDelivery {
            get {
                return ResourceManager.GetString("VlClintDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the price per kilo within the customer’s category of more than 10 kilos so that the process can be completed successfully....!.
        /// </summary>
        public static string VlClintPricePerkgAbove10 {
            get {
                return ResourceManager.GetString("VlClintPricePerkgAbove10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the local currency code for the operation to complete successfully..!.
        /// </summary>
        public static string Vlcode {
            get {
                return ResourceManager.GetString("Vlcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the company&apos;s delivery price so that the process can be completed successfully...!.
        /// </summary>
        public static string VlCompanyDelivery {
            get {
                return ResourceManager.GetString("VlCompanyDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the company&apos;s delivery price so that the process can be completed successfully...!.
        /// </summary>
        public static string VlCompanyDescription {
            get {
                return ResourceManager.GetString("VlCompanyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the company name for the process to complete successfully...!.
        /// </summary>
        public static string VlCompanyName {
            get {
                return ResourceManager.GetString("VlCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the price per kilo within the category higher than 10 kilograms received from the shipping company so that the process can be completed successfully....!.
        /// </summary>
        public static string VlCoPricePerkgAbove10 {
            get {
                return ResourceManager.GetString("VlCoPricePerkgAbove10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the price per kilo within the category of less than 10 kilograms received from the shipping company so that the process can be completed successfully....!.
        /// </summary>
        public static string VlCoPricePerkgUnder10 {
            get {
                return ResourceManager.GetString("VlCoPricePerkgUnder10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the country for the process to complete successfully...!.
        /// </summary>
        public static string VlCountry {
            get {
                return ResourceManager.GetString("VlCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string VlCurrency {
            get {
                return ResourceManager.GetString("VlCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter The Description.
        /// </summary>
        public static string VlDescription {
            get {
                return ResourceManager.GetString("VlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include a description of the link between the customer and the pricing. The process is completed successfully...!.
        /// </summary>
        public static string VlDescriptionClint {
            get {
                return ResourceManager.GetString("VlDescriptionClint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the order description for the process to complete successfully.
        /// </summary>
        public static string VlDescriptionOrder {
            get {
                return ResourceManager.GetString("VlDescriptionOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the nickname for the process to complete successfully..!.
        /// </summary>
        public static string VlEmail {
            get {
                return ResourceManager.GetString("VlEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the company&apos;s email so that the process is completed successfully...!.
        /// </summary>
        public static string VlEmailCompany {
            get {
                return ResourceManager.GetString("VlEmailCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VlFloor.
        /// </summary>
        public static string VlFloor {
            get {
                return ResourceManager.GetString("VlFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add the exchange rate in foreign currency for the process to complete successfully...!.
        /// </summary>
        public static string VlForeignCurrency {
            get {
                return ResourceManager.GetString("VlForeignCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the exchange rate in the local currency for the process to complete successfully...!.
        /// </summary>
        public static string VlGlobalExchangeRate {
            get {
                return ResourceManager.GetString("VlGlobalExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the exchange rate in the local currency for the process to complete successfully...!.
        /// </summary>
        public static string VllocalCurrency {
            get {
                return ResourceManager.GetString("VllocalCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VlMoblie.
        /// </summary>
        public static string VlMoblie {
            get {
                return ResourceManager.GetString("VlMoblie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the nickname for the process to complete successfully..!.
        /// </summary>
        public static string VlNikeNAme {
            get {
                return ResourceManager.GetString("VlNikeNAme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VlOffice.
        /// </summary>
        public static string VlOffice {
            get {
                return ResourceManager.GetString("VlOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the Password Email for the process to complete successfully...!.
        /// </summary>
        public static string VlPasswordEmail {
            get {
                return ResourceManager.GetString("VlPasswordEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter The Phone.
        /// </summary>
        public static string VlPhone {
            get {
                return ResourceManager.GetString("VlPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the phone number for the process to complete successfully....!.
        /// </summary>
        public static string VlPhoneCompany {
            get {
                return ResourceManager.GetString("VlPhoneCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit Amount.
        /// </summary>
        public static string VlProfitAmount {
            get {
                return ResourceManager.GetString("VlProfitAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include a bond number for the process to complete successfully...!.
        /// </summary>
        public static string VlReceiptNo {
            get {
                return ResourceManager.GetString("VlReceiptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the receipt statement for the process to be completed successfully....!.
        /// </summary>
        public static string VlReceiptStatment {
            get {
                return ResourceManager.GetString("VlReceiptStatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the amount for the transaction to complete successfully..!.
        /// </summary>
        public static string VlResivedMony {
            get {
                return ResourceManager.GetString("VlResivedMony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the Smtp Server for the process to complete successfully...!.
        /// </summary>
        public static string VlSmtpServer {
            get {
                return ResourceManager.GetString("VlSmtpServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Address.
        /// </summary>
        public static string VlShippingAddress {
            get {
                return ResourceManager.GetString("VlShippingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Street.
        /// </summary>
        public static string VlStreet {
            get {
                return ResourceManager.GetString("VlStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VlTitle.
        /// </summary>
        public static string VlTitle {
            get {
                return ResourceManager.GetString("VlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the appropriate address in the shipping category for the process to complete successfully...!.
        /// </summary>
        public static string VlTitleShipping {
            get {
                return ResourceManager.GetString("VlTitleShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered format must be the email format for the process to complete successfully...!.
        /// </summary>
        public static string VLTypEmail {
            get {
                return ResourceManager.GetString("VLTypEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the nickname for the process to complete successfully..!.
        /// </summary>
        public static string VlTypesCompanies {
            get {
                return ResourceManager.GetString("VlTypesCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the system type for the process to complete successfully..!.
        /// </summary>
        public static string VlTypeSystem {
            get {
                return ResourceManager.GetString("VlTypeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include the type of delivery system for the process to complete successfully...!.
        /// </summary>
        public static string VlTypeSystemDelivery {
            get {
                return ResourceManager.GetString("VlTypeSystemDelivery", resourceCulture);
            }
        }
    }
}
