//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domin.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domin.Resource.ResourceData", typeof(ResourceData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدراج السعر للكيلو ضمن فئة العميل أقل من 10 كيلو حتى تتم العملية بنجاح....!.
        /// </summary>
        public static string ClintPricePerkgUnder10 {
            get {
                return ResourceManager.GetString("ClintPricePerkgUnder10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك أعد كتابة كلمة المرور...!.
        /// </summary>
        public static string ComparePassword {
            get {
                return ResourceManager.GetString("ComparePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن تتطابق كلمات المرور...!.
        /// </summary>
        public static string ComparePasswordcomferm {
            get {
                return ResourceManager.GetString("ComparePasswordcomferm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الأحرف المدخلة لا يجب أن يتجاوز 100 حرف...!.
        /// </summary>
        public static string MaxLength100 {
            get {
                return ResourceManager.GetString("MaxLength100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الأحرف المدخلة لا يجب أن يتجاوز 1000 حرف...!.
        /// </summary>
        public static string MaxLength1000 {
            get {
                return ResourceManager.GetString("MaxLength1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الأحرف المدخلة لا يجب أن يتجاوز 20 حرفًا...!.
        /// </summary>
        public static string MaxLength20 {
            get {
                return ResourceManager.GetString("MaxLength20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الأحرف المدخلة لا يجب أن يتجاوز 2000 حرفًا...!.
        /// </summary>
        public static string MaxLength2000 {
            get {
                return ResourceManager.GetString("MaxLength2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الأحرف المدخلة لا يجب أن يتجاوز 25 حرفًا...!.
        /// </summary>
        public static string MaxLength25 {
            get {
                return ResourceManager.GetString("MaxLength25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الأحرف المدخلة لا يجب أن يتجاوز 300 حرفًا...!.
        /// </summary>
        public static string MaxLength300 {
            get {
                return ResourceManager.GetString("MaxLength300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الأحرف المدخلة لا يجب أن يتجاوز 500 حرفًا...!.
        /// </summary>
        public static string MaxLength500 {
            get {
                return ResourceManager.GetString("MaxLength500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الأحرف المدخلة لا يجب أن يقل عن حرف واحد، ويمكن استخدام الرمز # للإشارة إلى نفس الصفحة....!.
        /// </summary>
        public static string MinLength1 {
            get {
                return ResourceManager.GetString("MinLength1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الأحرف المدخلة لا يجب أن يقل عن 3 أحرف....!.
        /// </summary>
        public static string MinLength3 {
            get {
                return ResourceManager.GetString("MinLength3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الأحرف المدخلة لا يجب أن يقل عن 5 أحرف....!.
        /// </summary>
        public static string MinLength5 {
            get {
                return ResourceManager.GetString("MinLength5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ألا يقل عدد الأحرف في كلمة المرور عن 5 أحرف.
        /// </summary>
        public static string MinLengthPassword5 {
            get {
                return ResourceManager.GetString("MinLengthPassword5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك أدخل كلمة المرور لإتمام العملية بنجاح...!.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك أدخل رقم الهاتف...!.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى تضمين بريدك الإلكتروني..!.
        /// </summary>
        public static string RegisterEmail {
            get {
                return ResourceManager.GetString("RegisterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن يكون التنسيق المدخل هو تنسيق البريد الإلكتروني...!.
        /// </summary>
        public static string RegisterEmailError {
            get {
                return ResourceManager.GetString("RegisterEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رجاءا أدخل بريدك الإلكتروني...!.
        /// </summary>
        public static string RegisterEmaillogin {
            get {
                return ResourceManager.GetString("RegisterEmaillogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include full name.....!.
        /// </summary>
        public static string RegisterName {
            get {
                return ResourceManager.GetString("RegisterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك أدخل إذن المستخدم الخاص بك لإكمال العملية بنجاح..!.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب عليك إدخال اسم المستخدم...!.
        /// </summary>
        public static string userName {
            get {
                return ResourceManager.GetString("userName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى تضمين العنوان لإتمام العملية بنجاح.
        /// </summary>
        public static string VlAddres {
            get {
                return ResourceManager.GetString("VlAddres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى تضمين عنوان الشركة لإتمام العملية بنجاح...!.
        /// </summary>
        public static string VlAddresCompany {
            get {
                return ResourceManager.GetString("VlAddresCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدراج سعر الصرف بالعملة المحلية في السوق السوداء لإتمام العملية بنجاح....!.
        /// </summary>
        public static string VlBlackMarketExchangeRate {
            get {
                return ResourceManager.GetString("VlBlackMarketExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبنى.
        /// </summary>
        public static string VlBuilding {
            get {
                return ResourceManager.GetString("VlBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى تضمين إيصال الشحن.
        /// </summary>
        public static string VlCatchReceiptNo {
            get {
                return ResourceManager.GetString("VlCatchReceiptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى تضمين سعر توصيل العميل حتى تتم العملية بنجاح ...!.
        /// </summary>
        public static string VlClintDelivery {
            get {
                return ResourceManager.GetString("VlClintDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدراج السعر للكيلو ضمن فئة العميل التي تزيد عن 10 كيلو حتى تتم العملية بنجاح....!.
        /// </summary>
        public static string VlClintPricePerkgAbove10 {
            get {
                return ResourceManager.GetString("VlClintPricePerkgAbove10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى تضمين رمز العملة المحلية لإكمال العملية بنجاح..!.
        /// </summary>
        public static string Vlcode {
            get {
                return ResourceManager.GetString("Vlcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى تضمين سعر توصيل الشركة حتى تتم العملية بنجاح...!.
        /// </summary>
        public static string VlCompanyDelivery {
            get {
                return ResourceManager.GetString("VlCompanyDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى تضمين سعر توصيل الشركة حتى تتم العملية بنجاح...!.
        /// </summary>
        public static string VlCompanyDescription {
            get {
                return ResourceManager.GetString("VlCompanyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى تضمين اسم الشركة لإكمال العملية بنجاح ...!.
        /// </summary>
        public static string VlCompanyName {
            get {
                return ResourceManager.GetString("VlCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدراج السعر للكيلو ضمن الفئة الأعلى من 10 كيلو جرام المستلمة من شركة الشحن حتى تتم العملية بنجاح....!.
        /// </summary>
        public static string VlCoPricePerkgAbove10 {
            get {
                return ResourceManager.GetString("VlCoPricePerkgAbove10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدراج السعر للكيلو ضمن فئة أقل من 10 كيلو جرام المستلمة من شركة الشحن حتى تتم العملية بنجاح....!.
        /// </summary>
        public static string VlCoPricePerkgUnder10 {
            get {
                return ResourceManager.GetString("VlCoPricePerkgUnder10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى تضمين البلد لإكمال العملية بنجاح ...!.
        /// </summary>
        public static string VlCountry {
            get {
                return ResourceManager.GetString("VlCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العملة.
        /// </summary>
        public static string VlCurrency {
            get {
                return ResourceManager.GetString("VlCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى تضمين الوصف لإكمال العملية بنجاح ...!.
        /// </summary>
        public static string VlDescreption {
            get {
                return ResourceManager.GetString("VlDescreption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل الوصف.
        /// </summary>
        public static string VlDescription {
            get {
                return ResourceManager.GetString("VlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى تضمين وصف للرابط بين العميل والتسعير. تمت العملية بنجاح...!.
        /// </summary>
        public static string VlDescriptionClint {
            get {
                return ResourceManager.GetString("VlDescriptionClint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى تضمين وصف الطلب لإكمال العملية بنجاح.
        /// </summary>
        public static string VlDescriptionOrder {
            get {
                return ResourceManager.GetString("VlDescriptionOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى تضمين اللقب لإكمال العملية بنجاح..!.
        /// </summary>
        public static string VlEmail {
            get {
                return ResourceManager.GetString("VlEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدراج البريد الإلكتروني للشركة حتى تتم العملية بنجاح ...!.
        /// </summary>
        public static string VlEmailCompany {
            get {
                return ResourceManager.GetString("VlEmailCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى تضمين الأسئلة الشائعة لإكمالها بنجاح...!.
        /// </summary>
        public static string VlFAQ {
            get {
                return ResourceManager.GetString("VlFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطابق.
        /// </summary>
        public static string VlFloor {
            get {
                return ResourceManager.GetString("VlFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إضافة سعر الصرف بالعملة الأجنبية لإتمام العملية بنجاح...!.
        /// </summary>
        public static string VlForeignCurrency {
            get {
                return ResourceManager.GetString("VlForeignCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى تضمين سعر الصرف بالعملة المحلية لإتمام العملية بنجاح...!.
        /// </summary>
        public static string VlGlobalExchangeRate {
            get {
                return ResourceManager.GetString("VlGlobalExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى تضمين قائمة الأسئلة الشائعة لإكمال العملية بنجاح ...!.
        /// </summary>
        public static string VlListFAQ {
            get {
                return ResourceManager.GetString("VlListFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى تضمين سعر الصرف بالعملة المحلية لإتمام العملية بنجاح...!.
        /// </summary>
        public static string VllocalCurrency {
            get {
                return ResourceManager.GetString("VllocalCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى تضمين وصف الرسالة لإكمال العملية بنجاح...!.
        /// </summary>
        public static string VlMessageDescription {
            get {
                return ResourceManager.GetString("VlMessageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الموبايل.
        /// </summary>
        public static string VlMoblie {
            get {
                return ResourceManager.GetString("VlMoblie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى تضمين اللقب لإكمال العملية بنجاح..!.
        /// </summary>
        public static string VlNikeNAme {
            get {
                return ResourceManager.GetString("VlNikeNAme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مكتب.
        /// </summary>
        public static string VlOffice {
            get {
                return ResourceManager.GetString("VlOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى تضمين البريد الإلكتروني وكلمة المرور لإكمال العملية بنجاح ...!.
        /// </summary>
        public static string VlPasswordEmail {
            get {
                return ResourceManager.GetString("VlPasswordEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل رقم الهاتف.
        /// </summary>
        public static string VlPhone {
            get {
                return ResourceManager.GetString("VlPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى تضمين رقم الهاتف لإكمال العملية بنجاح....!.
        /// </summary>
        public static string VlPhoneCompany {
            get {
                return ResourceManager.GetString("VlPhoneCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المبلغ.
        /// </summary>
        public static string VlProfitAmount {
            get {
                return ResourceManager.GetString("VlProfitAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى تضمين رقم السند لإكمال العملية بنجاح...!.
        /// </summary>
        public static string VlReceiptNo {
            get {
                return ResourceManager.GetString("VlReceiptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى تضمين بيان الإيصال لإتمام العملية بنجاح....!.
        /// </summary>
        public static string VlReceiptStatment {
            get {
                return ResourceManager.GetString("VlReceiptStatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى تضمين المبلغ لإتمام المعاملة بنجاح..!.
        /// </summary>
        public static string VlResivedMony {
            get {
                return ResourceManager.GetString("VlResivedMony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان الشحن.
        /// </summary>
        public static string VlShippingAddress {
            get {
                return ResourceManager.GetString("VlShippingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى تضمين خادم Smtp لإكمال العملية بنجاح...!.
        /// </summary>
        public static string VlSmtpServer {
            get {
                return ResourceManager.GetString("VlSmtpServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل الشارع.
        /// </summary>
        public static string VlStreet {
            get {
                return ResourceManager.GetString("VlStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        public static string VlTitle {
            get {
                return ResourceManager.GetString("VlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى تضمين العنوان المناسب في فئة الشحن لإتمام العملية بنجاح...!.
        /// </summary>
        public static string VlTitleShipping {
            get {
                return ResourceManager.GetString("VlTitleShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن يكون التنسيق المدخل هو تنسيق البريد الإلكتروني حتى تكتمل العملية بنجاح...!.
        /// </summary>
        public static string VLTypEmail {
            get {
                return ResourceManager.GetString("VLTypEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى تضمين اللقب لإكمال العملية بنجاح..!.
        /// </summary>
        public static string VlTypesCompanies {
            get {
                return ResourceManager.GetString("VlTypesCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى تضمين أنواع الرسائل لإكمال العملية بنجاح ...!.
        /// </summary>
        public static string VlTypesOfMessage {
            get {
                return ResourceManager.GetString("VlTypesOfMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى تضمين أنواع الطلبات لإكمال العملية بنجاح ...!.
        /// </summary>
        public static string VlTypesOfRequest {
            get {
                return ResourceManager.GetString("VlTypesOfRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى تضمين نوع النظام لإكمال العملية بنجاح..!.
        /// </summary>
        public static string VlTypeSystem {
            get {
                return ResourceManager.GetString("VlTypeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى تضمين نوع نظام التسليم لإكمال العملية بنجاح ...!.
        /// </summary>
        public static string VlTypeSystemDelivery {
            get {
                return ResourceManager.GetString("VlTypeSystemDelivery", resourceCulture);
            }
        }
    }
}
