//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domin.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domin.Resource.ResourceData", typeof(ResourceData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج سعر الكيلو  ضمن فئة الاقل من 10 كيلو الخاص بالعميل  لتتم العملية بنجاح ....!.
        /// </summary>
        public static string ClintPricePerkgUnder10 {
            get {
                return ResourceManager.GetString("ClintPricePerkgUnder10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please retype the password...!.
        /// </summary>
        public static string ComparePassword {
            get {
                return ResourceManager.GetString("ComparePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must match...!.
        /// </summary>
        public static string ComparePasswordcomferm {
            get {
                return ResourceManager.GetString("ComparePasswordcomferm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الاحرف المدخلة عن100 حرف ...!.
        /// </summary>
        public static string MaxLength100 {
            get {
                return ResourceManager.GetString("MaxLength100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الاحرف المدخلة عن 20 حرف ...!.
        /// </summary>
        public static string MaxLength20 {
            get {
                return ResourceManager.GetString("MaxLength20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الاحرف المدخلة عن2000 حرف ...!.
        /// </summary>
        public static string MaxLength2000 {
            get {
                return ResourceManager.GetString("MaxLength2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الاحرف المدخلة عن 300 حرف ...!.
        /// </summary>
        public static string MaxLength300 {
            get {
                return ResourceManager.GetString("MaxLength300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الاحرف المدخلة عن 500 حرف ...!.
        /// </summary>
        public static string MaxLength500 {
            get {
                return ResourceManager.GetString("MaxLength500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يقل عدد الاحرف المدخلة عن حرف واحد ويمكن استخدم الرمز # لدلالة على نفس الصفحة   ....!.
        /// </summary>
        public static string MinLength1 {
            get {
                return ResourceManager.GetString("MinLength1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يقل عدد الاحرف المدخلة عن 3 أحرف  ....!.
        /// </summary>
        public static string MinLength3 {
            get {
                return ResourceManager.GetString("MinLength3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يقل عدد الاحرف المدخلة عن 5 أحرف  ....!.
        /// </summary>
        public static string MinLength5 {
            get {
                return ResourceManager.GetString("MinLength5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum number of characters for the password must be at least 5 characters.
        /// </summary>
        public static string MinLengthPassword5 {
            get {
                return ResourceManager.GetString("MinLengthPassword5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the password for the process to complete successfully...!.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter phone number...!.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include your email..!.
        /// </summary>
        public static string RegisterEmail {
            get {
                return ResourceManager.GetString("RegisterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entered format must be the email format...!.
        /// </summary>
        public static string RegisterEmailError {
            get {
                return ResourceManager.GetString("RegisterEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email...!.
        /// </summary>
        public static string RegisterEmaillogin {
            get {
                return ResourceManager.GetString("RegisterEmaillogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include full name.....!.
        /// </summary>
        public static string RegisterName {
            get {
                return ResourceManager.GetString("RegisterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your user permission for the process to complete successfully..!.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter the user name...!.
        /// </summary>
        public static string userName {
            get {
                return ResourceManager.GetString("userName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج عنوان الشركة لتتم العملية بنجاح ...!.
        /// </summary>
        public static string VlAddresCompany {
            get {
                return ResourceManager.GetString("VlAddresCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج سعر الصرف بالعملة المحلية في السوق السوداء لتتم العملية بنجاح....!.
        /// </summary>
        public static string VlBlackMarketExchangeRate {
            get {
                return ResourceManager.GetString("VlBlackMarketExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج سعر توصيل العميل لتتم العملية بنجاح...!.
        /// </summary>
        public static string VlClintDelivery {
            get {
                return ResourceManager.GetString("VlClintDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج سعر الكيلو  ضمن فئة الاعلى من 10 كيلو الخاص بالعميل  لتتم العملية بنجاح ....!.
        /// </summary>
        public static string VlClintPricePerkgAbove10 {
            get {
                return ResourceManager.GetString("VlClintPricePerkgAbove10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج رمز العملة المحلية لتتم العملية بنجاح ..!.
        /// </summary>
        public static string Vlcode {
            get {
                return ResourceManager.GetString("Vlcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج سعر توصيل الشركة لتتم العملية بنجاح ...!.
        /// </summary>
        public static string VlCompanyDelivery {
            get {
                return ResourceManager.GetString("VlCompanyDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج وصف الشركة لتتم العملية بنجاح ....!.
        /// </summary>
        public static string VlCompanyDescription {
            get {
                return ResourceManager.GetString("VlCompanyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج اسم الشركة لتتم العملية بنجاح ...!.
        /// </summary>
        public static string VlCompanyName {
            get {
                return ResourceManager.GetString("VlCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج سعر الكيلو  ضمن فئة  الاعلى من 10 كيلو الوارد من شركة الشحن لتتم العملية بنجاح ....!.
        /// </summary>
        public static string VlCoPricePerkgAbove10 {
            get {
                return ResourceManager.GetString("VlCoPricePerkgAbove10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج سعر الكيلو  ضمن فئة الاقل من 10 كيلو الوارد من شركة الشحن لتتم العملية بنجاح ....!.
        /// </summary>
        public static string VlCoPricePerkgUnder10 {
            get {
                return ResourceManager.GetString("VlCoPricePerkgUnder10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج الدولة لتتم العملية بنجاح ...!.
        /// </summary>
        public static string VlCountry {
            get {
                return ResourceManager.GetString("VlCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج بريد الشركة لتتم العملية بنجاح ...!.
        /// </summary>
        public static string VlEmailCompany {
            get {
                return ResourceManager.GetString("VlEmailCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أضافة سعر الصرف بالعملة الاجنبية لتتم العملية بنجاح ...!.
        /// </summary>
        public static string VlForeignCurrency {
            get {
                return ResourceManager.GetString("VlForeignCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج سعر الصرف بالعملة المحلية لتتم العملية بنجاح ...!.
        /// </summary>
        public static string VlGlobalExchangeRate {
            get {
                return ResourceManager.GetString("VlGlobalExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى ادراج اسم العملة المحلية لتتم العملية بنجاح ...!.
        /// </summary>
        public static string VllocalCurrency {
            get {
                return ResourceManager.GetString("VllocalCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج الاسم المستعار لتتم العملية بنجاح ..!.
        /// </summary>
        public static string VlNikeNAme {
            get {
                return ResourceManager.GetString("VlNikeNAme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى ادراج رقم الهاتف لتتم العملية بنجاح ....!.
        /// </summary>
        public static string VlPhoneCompany {
            get {
                return ResourceManager.GetString("VlPhoneCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج العنوان المناسب الخاص في فئة الشحن لتتم العملية بنجاح ...!.
        /// </summary>
        public static string VlTitleShipping {
            get {
                return ResourceManager.GetString("VlTitleShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن تكون الصيغة المدخلة صيغة البريد الاكتروني  لتتم العملية بنجاح ...!.
        /// </summary>
        public static string VLTypEmail {
            get {
                return ResourceManager.GetString("VLTypEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى أدراج نوع الشركة لتتم العملية بنجاح .....!.
        /// </summary>
        public static string VlTypesCompanies {
            get {
                return ResourceManager.GetString("VlTypesCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدراج نوع النظام لتتم العملية بنجاح ..!.
        /// </summary>
        public static string VlTypeSystem {
            get {
                return ResourceManager.GetString("VlTypeSystem", resourceCulture);
            }
        }
    }
}
