//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yara.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceWeb {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceWeb() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yara.Resource.ResourceWeb", typeof(ResourceWeb).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealing status.
        /// </summary>
        public static string LbActive {
            get {
                return ResourceManager.GetString("LbActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active User.
        /// </summary>
        public static string LbActiveUser {
            get {
                return ResourceManager.GetString("LbActiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding and modifying regions.
        /// </summary>
        public static string LBAddArea {
            get {
                return ResourceManager.GetString("LBAddArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding and modifying the pricing of delivery companies for the regions.
        /// </summary>
        public static string LBAddAreaDeliveryTariffs {
            get {
                return ResourceManager.GetString("LBAddAreaDeliveryTariffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding and modifying city data.
        /// </summary>
        public static string LBAddCity {
            get {
                return ResourceManager.GetString("LBAddCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding and modifying the pricing of delivery companies to cities.
        /// </summary>
        public static string LBAddCityDeliveryTariffs {
            get {
                return ResourceManager.GetString("LBAddCityDeliveryTariffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding and modifying systems Clint Withe Delivery Tariffs.
        /// </summary>
        public static string LBAddClintWitheDeliveryTariffs {
            get {
                return ResourceManager.GetString("LBAddClintWitheDeliveryTariffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add and modify currencies.
        /// </summary>
        public static string LBAddCurrenciesExchangeRates {
            get {
                return ResourceManager.GetString("LBAddCurrenciesExchangeRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add and modify company data.
        /// </summary>
        public static string LbAddEditInformationCompanies {
            get {
                return ResourceManager.GetString("LbAddEditInformationCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding and modifying Email Alart Setting.
        /// </summary>
        public static string LBAddEmailAlartSetting {
            get {
                return ResourceManager.GetString("LBAddEmailAlartSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add and modify the exchange rate.
        /// </summary>
        public static string LBAddExchangeRate {
            get {
                return ResourceManager.GetString("LBAddExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding and modifying Order Case.
        /// </summary>
        public static string LBAddOrderCase {
            get {
                return ResourceManager.GetString("LBAddOrderCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding and modifying Add Order New.
        /// </summary>
        public static string LBAddOrderNew {
            get {
                return ResourceManager.GetString("LBAddOrderNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding and modifying Order Status.
        /// </summary>
        public static string LBAddOrderStatus {
            get {
                return ResourceManager.GetString("LBAddOrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Paing.
        /// </summary>
        public static string LBAddPaing {
            get {
                return ResourceManager.GetString("LBAddPaing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Profit.
        /// </summary>
        public static string LBAddProfit {
            get {
                return ResourceManager.GetString("LBAddProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string LbAddres {
            get {
                return ResourceManager.GetString("LbAddres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string LbAddresCompany {
            get {
                return ResourceManager.GetString("LbAddresCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding and modifying Roles.
        /// </summary>
        public static string LBAddRolesName {
            get {
                return ResourceManager.GetString("LBAddRolesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Shipping Address.
        /// </summary>
        public static string LBAddShippingAddress {
            get {
                return ResourceManager.GetString("LBAddShippingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding and modifying pricing for shipping systems.
        /// </summary>
        public static string LBAddShippingPrice {
            get {
                return ResourceManager.GetString("LBAddShippingPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding and modifying Task Status.
        /// </summary>
        public static string LBAddTaskStatus {
            get {
                return ResourceManager.GetString("LBAddTaskStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add and modify currency calculator.
        /// </summary>
        public static string LBAddTransaction {
            get {
                return ResourceManager.GetString("LBAddTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding and modifying Transfer.
        /// </summary>
        public static string LBAddTransfer {
            get {
                return ResourceManager.GetString("LBAddTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add and modify company categories.
        /// </summary>
        public static string LBAddTypesCompanies {
            get {
                return ResourceManager.GetString("LBAddTypesCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding and modifying Types Of Message.
        /// </summary>
        public static string LBAddTypesOfMessage {
            get {
                return ResourceManager.GetString("LBAddTypesOfMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding and modifying Types Of Request.
        /// </summary>
        public static string LBAddTypesOfRequest {
            get {
                return ResourceManager.GetString("LBAddTypesOfRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding and modifying systems.
        /// </summary>
        public static string LBAddTypeSystem {
            get {
                return ResourceManager.GetString("LBAddTypeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding and modifying Type System Delivery.
        /// </summary>
        public static string LBAddTypeSystemDelivery {
            get {
                return ResourceManager.GetString("LBAddTypeSystemDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string LbAmount {
            get {
                return ResourceManager.GetString("LbAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bgw.
        /// </summary>
        public static string Lbbgw {
            get {
                return ResourceManager.GetString("Lbbgw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to branch.
        /// </summary>
        public static string Lbbranch {
            get {
                return ResourceManager.GetString("Lbbranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building.
        /// </summary>
        public static string LBBuilding {
            get {
                return ResourceManager.GetString("LBBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bypass.
        /// </summary>
        public static string Lbbypass {
            get {
                return ResourceManager.GetString("Lbbypass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catch Receipt No.
        /// </summary>
        public static string LbCatchReceiptNo {
            get {
                return ResourceManager.GetString("LbCatchReceiptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string LbCity {
            get {
                return ResourceManager.GetString("LbCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery price to the customer.
        /// </summary>
        public static string LbClintDelivery {
            get {
                return ResourceManager.GetString("LbClintDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clint Information.
        /// </summary>
        public static string LBClintInformation {
            get {
                return ResourceManager.GetString("LBClintInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer shipping price is more than 10.
        /// </summary>
        public static string LbClintPricePerkgAbove10 {
            get {
                return ResourceManager.GetString("LbClintPricePerkgAbove10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer shipping price is less than 10.
        /// </summary>
        public static string LbClintPricePerkgUnder10 {
            get {
                return ResourceManager.GetString("LbClintPricePerkgUnder10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code.
        /// </summary>
        public static string Lbcode {
            get {
                return ResourceManager.GetString("Lbcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code.
        /// </summary>
        public static string Lbcodeto {
            get {
                return ResourceManager.GetString("Lbcodeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery company pricing.
        /// </summary>
        public static string LbCompanyDelivery {
            get {
                return ResourceManager.GetString("LbCompanyDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company description.
        /// </summary>
        public static string LbCompanyDescription {
            get {
                return ResourceManager.GetString("LbCompanyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string LbCompanyName {
            get {
                return ResourceManager.GetString("LbCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant Company Namem.
        /// </summary>
        public static string LbCompanyNamem {
            get {
                return ResourceManager.GetString("LbCompanyNamem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموقع الاكتروني.
        /// </summary>
        public static string LbCompanyURl {
            get {
                return ResourceManager.GetString("LbCompanyURl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المبلغ المحول.
        /// </summary>
        public static string LbConvertedAmount {
            get {
                return ResourceManager.GetString("LbConvertedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The company&apos;s shipping price is more than 10.
        /// </summary>
        public static string LbCoPricePerkgAbove10 {
            get {
                return ResourceManager.GetString("LbCoPricePerkgAbove10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The company&apos;s shipping price is less than 10.
        /// </summary>
        public static string LbCoPricePerkgUnder10 {
            get {
                return ResourceManager.GetString("LbCoPricePerkgUnder10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Price.
        /// </summary>
        public static string LbCostPrice {
            get {
                return ResourceManager.GetString("LbCostPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  currency.
        /// </summary>
        public static string LbCountry {
            get {
                return ResourceManager.GetString("LbCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange rate to.
        /// </summary>
        public static string LbCountryto {
            get {
                return ResourceManager.GetString("LbCountryto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to credit.
        /// </summary>
        public static string Lbcredit {
            get {
                return ResourceManager.GetString("Lbcredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string LbCurrency {
            get {
                return ResourceManager.GetString("LbCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to status.
        /// </summary>
        public static string lbCurrentState {
            get {
                return ResourceManager.GetString("lbCurrentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearest Teacher.
        /// </summary>
        public static string Lbcust_landmark {
            get {
                return ResourceManager.GetString("Lbcust_landmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone1.
        /// </summary>
        public static string Lbcust_mob {
            get {
                return ResourceManager.GetString("Lbcust_mob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone2.
        /// </summary>
        public static string Lbcust_mob2 {
            get {
                return ResourceManager.GetString("Lbcust_mob2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string Lbcust_name {
            get {
                return ResourceManager.GetString("Lbcust_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Lbcust_profile {
            get {
                return ResourceManager.GetString("Lbcust_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to old status.
        /// </summary>
        public static string Lbcust_status {
            get {
                return ResourceManager.GetString("Lbcust_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer On Order.
        /// </summary>
        public static string LBCustomeronorder {
            get {
                return ResourceManager.GetString("LBCustomeronorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string LBCustomers {
            get {
                return ResourceManager.GetString("LBCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data entry.
        /// </summary>
        public static string LbDataEntry {
            get {
                return ResourceManager.GetString("LbDataEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time and date of entry.
        /// </summary>
        public static string LbDateTimeEntry {
            get {
                return ResourceManager.GetString("LbDateTimeEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Charges.
        /// </summary>
        public static string Lbdelivery_charges {
            get {
                return ResourceManager.GetString("Lbdelivery_charges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeliveryAddress.
        /// </summary>
        public static string LBDeliveryAddress {
            get {
                return ResourceManager.GetString("LBDeliveryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string LbDescription {
            get {
                return ResourceManager.GetString("LbDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Lbdescriptioncity {
            get {
                return ResourceManager.GetString("Lbdescriptioncity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Clint.
        /// </summary>
        public static string LbDescriptionClint {
            get {
                return ResourceManager.GetString("LbDescriptionClint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Order.
        /// </summary>
        public static string LbDescriptionOrder {
            get {
                return ResourceManager.GetString("LbDescriptionOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Order Status.
        /// </summary>
        public static string LbdescriptionOrderStuse {
            get {
                return ResourceManager.GetString("LbdescriptionOrderStuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image size 150*150.
        /// </summary>
        public static string LBEmageSise {
            get {
                return ResourceManager.GetString("LBEmageSise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailAlart Setting.
        /// </summary>
        public static string LbEmailAlartSetting {
            get {
                return ResourceManager.GetString("LbEmailAlartSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string LbEmailCompany {
            get {
                return ResourceManager.GetString("LbEmailCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Amount.
        /// </summary>
        public static string LbExchangeAmount {
            get {
                return ResourceManager.GetString("LbExchangeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchanged Price.
        /// </summary>
        public static string LbExchangedPrice {
            get {
                return ResourceManager.GetString("LbExchangedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exchange rate.
        /// </summary>
        public static string LbExchangeRate {
            get {
                return ResourceManager.GetString("LbExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fb.
        /// </summary>
        public static string Lbfbid {
            get {
                return ResourceManager.GetString("Lbfbid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        public static string LBFloor {
            get {
                return ResourceManager.GetString("LBFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full package.
        /// </summary>
        public static string Lbfull_package {
            get {
                return ResourceManager.GetString("Lbfull_package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        public static string LBGeneralSettings {
            get {
                return ResourceManager.GetString("LBGeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Lbgisurl {
            get {
                return ResourceManager.GetString("Lbgisurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code.
        /// </summary>
        public static string Lbhexcode {
            get {
                return ResourceManager.GetString("Lbhexcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hidden.
        /// </summary>
        public static string Lbhidden {
            get {
                return ResourceManager.GetString("Lbhidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hxcode.
        /// </summary>
        public static string LBhxcode {
            get {
                return ResourceManager.GetString("LBhxcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string LbId {
            get {
                return ResourceManager.GetString("LbId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to information.
        /// </summary>
        public static string LbInformaition {
            get {
                return ResourceManager.GetString("LbInformaition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customer information.
        /// </summary>
        public static string LbInformaitioncl {
            get {
                return ResourceManager.GetString("LbInformaitioncl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to company information.
        /// </summary>
        public static string LbInformaitionco {
            get {
                return ResourceManager.GetString("LbInformaitionco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Company.
        /// </summary>
        public static string LbInformationCompany {
            get {
                return ResourceManager.GetString("LbInformationCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date added.
        /// </summary>
        public static string Lbinsert_dt {
            get {
                return ResourceManager.GetString("Lbinsert_dt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The South.
        /// </summary>
        public static string LbIsNorth {
            get {
                return ResourceManager.GetString("LbIsNorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string lbIsPaid {
            get {
                return ResourceManager.GetString("lbIsPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to isPublic.
        /// </summary>
        public static string LbisPublic {
            get {
                return ResourceManager.GetString("LbisPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Lblat {
            get {
                return ResourceManager.GetString("Lblat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Name.
        /// </summary>
        public static string LBLbAreaName {
            get {
                return ResourceManager.GetString("LBLbAreaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string LBLbRoles {
            get {
                return ResourceManager.GetString("LBLbRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to longitude.
        /// </summary>
        public static string Lblon {
            get {
                return ResourceManager.GetString("Lblon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Sender.
        /// </summary>
        public static string lbMailSender {
            get {
                return ResourceManager.GetString("lbMailSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phone number.
        /// </summary>
        public static string Lbmerchant_mob {
            get {
                return ResourceManager.GetString("Lbmerchant_mob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant name.
        /// </summary>
        public static string LbMerchant_name {
            get {
                return ResourceManager.GetString("LbMerchant_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant Information.
        /// </summary>
        public static string LBMerchantInformation {
            get {
                return ResourceManager.GetString("LBMerchantInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchants.
        /// </summary>
        public static string LBMerchants {
            get {
                return ResourceManager.GetString("LBMerchants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error User Name Or Password.....!.
        /// </summary>
        public static string lbMsgErrorLogin {
            get {
                return ResourceManager.GetString("lbMsgErrorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error The new password was not saved...!.
        /// </summary>
        public static string lbMsgNotSavedChangePassword {
            get {
                return ResourceManager.GetString("lbMsgNotSavedChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password was saved successfully.
        /// </summary>
        public static string lbMsgSavedChangePassword {
            get {
                return ResourceManager.GetString("lbMsgSavedChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regions.
        /// </summary>
        public static string LBMyArea {
            get {
                return ResourceManager.GetString("LBMyArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing of delivery companies to the regions.
        /// </summary>
        public static string LBMyAreaDeliveryTariffs {
            get {
                return ResourceManager.GetString("LBMyAreaDeliveryTariffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities data.
        /// </summary>
        public static string LBMyCity {
            get {
                return ResourceManager.GetString("LBMyCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing of delivery companies to cities.
        /// </summary>
        public static string LBMyCityDeliveryTariffs {
            get {
                return ResourceManager.GetString("LBMyCityDeliveryTariffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clint Withe Delivery Tariffs.
        /// </summary>
        public static string LBMyClintWitheDeliveryTariffs {
            get {
                return ResourceManager.GetString("LBMyClintWitheDeliveryTariffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies.
        /// </summary>
        public static string LBMyCurrenciesExchangeRates {
            get {
                return ResourceManager.GetString("LBMyCurrenciesExchangeRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual customer data.
        /// </summary>
        public static string LBMyCustomer {
            get {
                return ResourceManager.GetString("LBMyCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Alart Setting.
        /// </summary>
        public static string LBMyEmailAlartSetting {
            get {
                return ResourceManager.GetString("LBMyEmailAlartSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exchange rate.
        /// </summary>
        public static string LBMyExchangeRate {
            get {
                return ResourceManager.GetString("LBMyExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Companies.
        /// </summary>
        public static string LBMYInformationCompanies {
            get {
                return ResourceManager.GetString("LBMYInformationCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchants&apos; data.
        /// </summary>
        public static string LBMyMerchant {
            get {
                return ResourceManager.GetString("LBMyMerchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string LBMyOrder {
            get {
                return ResourceManager.GetString("LBMyOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Cases.
        /// </summary>
        public static string LBMyOrderCase {
            get {
                return ResourceManager.GetString("LBMyOrderCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order New .
        /// </summary>
        public static string LBMyOrderNew {
            get {
                return ResourceManager.GetString("LBMyOrderNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Status.
        /// </summary>
        public static string LBMyOrderStatus {
            get {
                return ResourceManager.GetString("LBMyOrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profits.
        /// </summary>
        public static string LBMyProfits {
            get {
                return ResourceManager.GetString("LBMyProfits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles .
        /// </summary>
        public static string LBMyRolesName {
            get {
                return ResourceManager.GetString("LBMyRolesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyShipping Address.
        /// </summary>
        public static string LBMyShippingAddress {
            get {
                return ResourceManager.GetString("LBMyShippingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping systems pricing.
        /// </summary>
        public static string LBMyShippingPrice {
            get {
                return ResourceManager.GetString("LBMyShippingPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Status.
        /// </summary>
        public static string LBMyTaskStatus {
            get {
                return ResourceManager.GetString("LBMyTaskStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency calculator.
        /// </summary>
        public static string LBMyTransaction {
            get {
                return ResourceManager.GetString("LBMyTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Transfers.
        /// </summary>
        public static string LBMyTransfers {
            get {
                return ResourceManager.GetString("LBMyTransfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories of companies.
        /// </summary>
        public static string LBMyTypesCompanies {
            get {
                return ResourceManager.GetString("LBMyTypesCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types Of Message.
        /// </summary>
        public static string LBMyTypesOfMessage {
            get {
                return ResourceManager.GetString("LBMyTypesOfMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types Of Request.
        /// </summary>
        public static string LBMyTypesOfRequest {
            get {
                return ResourceManager.GetString("LBMyTypesOfRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Systems.
        /// </summary>
        public static string LBMyTypeSystem {
            get {
                return ResourceManager.GetString("LBMyTypeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type System Delivery.
        /// </summary>
        public static string LBMyTypeSystemDelivery {
            get {
                return ResourceManager.GetString("LBMyTypeSystemDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string LbName {
            get {
                return ResourceManager.GetString("LbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NameRols.
        /// </summary>
        public static string LbNameRols {
            get {
                return ResourceManager.GetString("LbNameRols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nick name.
        /// </summary>
        public static string LbNikeNAme {
            get {
                return ResourceManager.GetString("LbNikeNAme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant Company Namem.
        /// </summary>
        public static string LbNikeNAmeM {
            get {
                return ResourceManager.GetString("LbNikeNAmeM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normalized Name.
        /// </summary>
        public static string LbNormalizedName {
            get {
                return ResourceManager.GetString("LbNormalizedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Lbnotes {
            get {
                return ResourceManager.GetString("Lbnotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving. Please check and try again later...!.
        /// </summary>
        public static string lbNotSaved {
            get {
                return ResourceManager.GetString("lbNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The validity process was not saved, please check and try again later.
        /// </summary>
        public static string lbNotSavedMsgRole {
            get {
                return ResourceManager.GetString("lbNotSavedMsgRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The validity process was not saved, please check and try again later.
        /// </summary>
        public static string lbNotSavedMsgUser {
            get {
                return ResourceManager.GetString("lbNotSavedMsgUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The validity process was not saved, please check and try again later.
        /// </summary>
        public static string lbNotSavedMsgUserRole {
            get {
                return ResourceManager.GetString("lbNotSavedMsgUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during the editing process. Please check and try again later..!.
        /// </summary>
        public static string lbNotUpdate {
            get {
                return ResourceManager.GetString("lbNotUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during the editing process. Please check and try again later..!.
        /// </summary>
        public static string lbNotUpdateMsgRole {
            get {
                return ResourceManager.GetString("lbNotUpdateMsgRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during the editing process. Please check and try again later..!.
        /// </summary>
        public static string lbNotUpdateMsgUser {
            get {
                return ResourceManager.GetString("lbNotUpdateMsgUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during the editing process. Please check and try again later..!.
        /// </summary>
        public static string lbNotUpdateMsgUserRole {
            get {
                return ResourceManager.GetString("lbNotUpdateMsgUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noute.
        /// </summary>
        public static string LbNouts {
            get {
                return ResourceManager.GetString("LbNouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouts Order.
        /// </summary>
        public static string LbNoutsOrder {
            get {
                return ResourceManager.GetString("LbNoutsOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office.
        /// </summary>
        public static string LbOffice {
            get {
                return ResourceManager.GetString("LbOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old photo.
        /// </summary>
        public static string lbOldeAndUserGide {
            get {
                return ResourceManager.GetString("lbOldeAndUserGide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processes.
        /// </summary>
        public static string LbOpration {
            get {
                return ResourceManager.GetString("LbOpration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case.
        /// </summary>
        public static string LbOrderCase {
            get {
                return ResourceManager.GetString("LbOrderCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Cases.
        /// </summary>
        public static string LborderCases {
            get {
                return ResourceManager.GetString("LborderCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date.
        /// </summary>
        public static string LbOrderDate {
            get {
                return ResourceManager.GetString("LbOrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Information.
        /// </summary>
        public static string LBOrderInformation {
            get {
                return ResourceManager.GetString("LBOrderInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders System.
        /// </summary>
        public static string LBOrdersSystem {
            get {
                return ResourceManager.GetString("LBOrdersSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Status.
        /// </summary>
        public static string LBOrderStatus {
            get {
                return ResourceManager.GetString("LBOrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to outskirts.
        /// </summary>
        public static string Lboutskirts {
            get {
                return ResourceManager.GetString("Lboutskirts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paiding Informations.
        /// </summary>
        public static string LBPaidingInformations {
            get {
                return ResourceManager.GetString("LBPaidingInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paidings.
        /// </summary>
        public static string LBPaidings {
            get {
                return ResourceManager.GetString("LBPaidings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Email.
        /// </summary>
        public static string lbPasswordEmail {
            get {
                return ResourceManager.GetString("lbPasswordEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phone.
        /// </summary>
        public static string LbPhoneCompany {
            get {
                return ResourceManager.GetString("LbPhoneCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone 2.
        /// </summary>
        public static string LbPhoneCompanySecand {
            get {
                return ResourceManager.GetString("LbPhoneCompanySecand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string LbPhoto {
            get {
                return ResourceManager.GetString("LbPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Server.
        /// </summary>
        public static string lbPortServer {
            get {
                return ResourceManager.GetString("lbPortServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string LbPrice {
            get {
                return ResourceManager.GetString("LbPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing System.
        /// </summary>
        public static string LBPricingSystem {
            get {
                return ResourceManager.GetString("LBPricingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string LBProfile {
            get {
                return ResourceManager.GetString("LBProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit Amount.
        /// </summary>
        public static string LbProfitAmount {
            get {
                return ResourceManager.GetString("LbProfitAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profits.
        /// </summary>
        public static string LbProfits {
            get {
                return ResourceManager.GetString("LbProfits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profits Informations.
        /// </summary>
        public static string LBProfitsInformations {
            get {
                return ResourceManager.GetString("LBProfitsInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exchange rate.
        /// </summary>
        public static string LbRate {
            get {
                return ResourceManager.GetString("LbRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Date.
        /// </summary>
        public static string LBreceipt_dt {
            get {
                return ResourceManager.GetString("LBreceipt_dt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt No.
        /// </summary>
        public static string LBreceipt_no {
            get {
                return ResourceManager.GetString("LBreceipt_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Statment.
        /// </summary>
        public static string LbReceiptStatment {
            get {
                return ResourceManager.GetString("LbReceiptStatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resived Money.
        /// </summary>
        public static string LbResivedMony {
            get {
                return ResourceManager.GetString("LbResivedMony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Lbrole {
            get {
                return ResourceManager.GetString("Lbrole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles Name.
        /// </summary>
        public static string LbRolesName {
            get {
                return ResourceManager.GetString("LbRolesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string lbSave {
            get {
                return ResourceManager.GetString("lbSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string lbSaveMsgRole {
            get {
                return ResourceManager.GetString("lbSaveMsgRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sector.
        /// </summary>
        public static string LbSector {
            get {
                return ResourceManager.GetString("LbSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Charges.
        /// </summary>
        public static string LBservice_charges {
            get {
                return ResourceManager.GetString("LBservice_charges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Address.
        /// </summary>
        public static string LBShippingAddress {
            get {
                return ResourceManager.GetString("LBShippingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Address Info.
        /// </summary>
        public static string LBShippingAddressInfo {
            get {
                return ResourceManager.GetString("LBShippingAddressInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Address Location.
        /// </summary>
        public static string LBShippingAddressLocation {
            get {
                return ResourceManager.GetString("LBShippingAddressLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  sms alert.
        /// </summary>
        public static string Lbsms_alert {
            get {
                return ResourceManager.GetString("Lbsms_alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smtp Server.
        /// </summary>
        public static string lbSmtpServer {
            get {
                return ResourceManager.GetString("lbSmtpServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorting.
        /// </summary>
        public static string Lbsorting {
            get {
                return ResourceManager.GetString("Lbsorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space.
        /// </summary>
        public static string LbSpec {
            get {
                return ResourceManager.GetString("LbSpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ssl validity.
        /// </summary>
        public static string lbSsl_validity {
            get {
                return ResourceManager.GetString("lbSsl_validity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string LBStreet {
            get {
                return ResourceManager.GetString("LBStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Status.
        /// </summary>
        public static string LbTaskStatus {
            get {
                return ResourceManager.GetString("LbTaskStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string LbTitle {
            get {
                return ResourceManager.GetString("LbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Shipping.
        /// </summary>
        public static string LbTitleShipping {
            get {
                return ResourceManager.GetString("LbTitleShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Amount.
        /// </summary>
        public static string LbTransferAmount {
            get {
                return ResourceManager.GetString("LbTransferAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Informations.
        /// </summary>
        public static string LBTransferInformations {
            get {
                return ResourceManager.GetString("LBTransferInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string LbTypesCompanies {
            get {
                return ResourceManager.GetString("LbTypesCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant Types Companies.
        /// </summary>
        public static string LbTypesCompaniesM {
            get {
                return ResourceManager.GetString("LbTypesCompaniesM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Message.
        /// </summary>
        public static string LbTypesOfMessage {
            get {
                return ResourceManager.GetString("LbTypesOfMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types.
        /// </summary>
        public static string LbTypesOfRequest {
            get {
                return ResourceManager.GetString("LbTypesOfRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to system.
        /// </summary>
        public static string LbTypeSystem {
            get {
                return ResourceManager.GetString("LbTypeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string lbUpdate {
            get {
                return ResourceManager.GetString("lbUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string lbUpdateMsgRole {
            get {
                return ResourceManager.GetString("lbUpdateMsgRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upload.
        /// </summary>
        public static string LBUpload_image {
            get {
                return ResourceManager.GetString("LBUpload_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery system user.
        /// </summary>
        public static string LbUS_delivery {
            get {
                return ResourceManager.GetString("LbUS_delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string LbUserEmage {
            get {
                return ResourceManager.GetString("LbUserEmage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Email.
        /// </summary>
        public static string LbUserEmail {
            get {
                return ResourceManager.GetString("LbUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string LbUserName {
            get {
                return ResourceManager.GetString("LbUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string LbUserPhone {
            get {
                return ResourceManager.GetString("LbUserPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to userpwd.
        /// </summary>
        public static string Lbuserpwd {
            get {
                return ResourceManager.GetString("Lbuserpwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Information.
        /// </summary>
        public static string LBUsersInformationEn {
            get {
                return ResourceManager.GetString("LBUsersInformationEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string LbWeight {
            get {
                return ResourceManager.GetString("LbWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with Delivery.
        /// </summary>
        public static string Lbwith_delivery {
            get {
                return ResourceManager.GetString("Lbwith_delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residential quarter.
        /// </summary>
        public static string LbZone {
            get {
                return ResourceManager.GetString("LbZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description of shipping validity.
        /// </summary>
        public static string LTitleShipping {
            get {
                return ResourceManager.GetString("LTitleShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt No.
        /// </summary>
        public static string ReceiptNo {
            get {
                return ResourceManager.GetString("ReceiptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pricing has already been added to the region. Please check and try again later...!.
        /// </summary>
        public static string VLAreadoplceted {
            get {
                return ResourceManager.GetString("VLAreadoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The receipt voucher number has already been entered. Please verify and try again later...!.
        /// </summary>
        public static string VLCatchReceiptNoDoplceted {
            get {
                return ResourceManager.GetString("VLCatchReceiptNoDoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delivery price for this city has been entered. Please check and try again later...!.
        /// </summary>
        public static string VLCitydoplceted {
            get {
                return ResourceManager.GetString("VLCitydoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The company has already been entered. Please check and try again later....!.
        /// </summary>
        public static string VLCompanyNameDoplceted {
            get {
                return ResourceManager.GetString("VLCompanyNameDoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The country has already been entered. Please check and try again later...!.
        /// </summary>
        public static string VLCountryDoplceted {
            get {
                return ResourceManager.GetString("VLCountryDoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer&apos;s phone has already been entered. Please confirm and try again later...!.
        /// </summary>
        public static string VLCustMob2doplceted {
            get {
                return ResourceManager.GetString("VLCustMob2doplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer&apos;s phone has already been entered. Please confirm and try again later...!.
        /// </summary>
        public static string VLCustMobdoplceted {
            get {
                return ResourceManager.GetString("VLCustMobdoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer name has already been entered. Please verify and try again later....!.
        /// </summary>
        public static string VLCustNamedoplceted {
            get {
                return ResourceManager.GetString("VLCustNamedoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer has been introduced to the pricing system. Please confirm and try again later...!.
        /// </summary>
        public static string VLCustomerDoplceted {
            get {
                return ResourceManager.GetString("VLCustomerDoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The deletion was not completed. There was an error.
        /// </summary>
        public static string VLDeleteError {
            get {
                return ResourceManager.GetString("VLDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The deletion was completed successfully.
        /// </summary>
        public static string VLDeletesuccessful {
            get {
                return ResourceManager.GetString("VLDeletesuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The deletion was completed successfully.
        /// </summary>
        public static string VLdELETESuccessfully {
            get {
                return ResourceManager.GetString("VLdELETESuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The region has already been entered. Please verify and try again later...!.
        /// </summary>
        public static string VLDescriptionareadoplceted {
            get {
                return ResourceManager.GetString("VLDescriptionareadoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description of the connection to the tariff system has already been entered. Please verify and try again later...!.
        /// </summary>
        public static string VLDescriptionClintDoplceted {
            get {
                return ResourceManager.GetString("VLDescriptionClintDoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city has already been entered. Please check and try again later....!.
        /// </summary>
        public static string VLDescriptionDoplceted {
            get {
                return ResourceManager.GetString("VLDescriptionDoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order status has been entered. Please confirm and try again later....!.
        /// </summary>
        public static string VLDescriptiondplceted {
            get {
                return ResourceManager.GetString("VLDescriptiondplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The order description has already been entered. Please confirm and try again later...!.
        /// </summary>
        public static string VLDescriptionOrderDoplceted {
            get {
                return ResourceManager.GetString("VLDescriptionOrderDoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email address has already been entered, please check and try again later..!.
        /// </summary>
        public static string VLEmailAlartSettingDoplceted {
            get {
                return ResourceManager.GetString("VLEmailAlartSettingDoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shipping refund email has already been entered. Please check and try again later....!.
        /// </summary>
        public static string VLEmailDoplceted {
            get {
                return ResourceManager.GetString("VLEmailDoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or username already exists...!.
        /// </summary>
        public static string VLEmailOreUserOrPaswo {
            get {
                return ResourceManager.GetString("VLEmailOreUserOrPaswo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion error...!.
        /// </summary>
        public static string VLErrorDeleteData {
            get {
                return ResourceManager.GetString("VLErrorDeleteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during saving process....!.
        /// </summary>
        public static string VLErrorSave {
            get {
                return ResourceManager.GetString("VLErrorSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in the editing process....!.
        /// </summary>
        public static string VLErrorUpdate {
            get {
                return ResourceManager.GetString("VLErrorUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The currency has already been entered. Please check and try again later...!.
        /// </summary>
        public static string VLExchangeRateDoplceted {
            get {
                return ResourceManager.GetString("VLExchangeRateDoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The question has already been entered.. Please check and try again later..!.
        /// </summary>
        public static string VLFAQDoplceted {
            get {
                return ResourceManager.GetString("VLFAQDoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code has already been entered, please verify and try again later...!.
        /// </summary>
        public static string VLHxcodedoplceted {
            get {
                return ResourceManager.GetString("VLHxcodedoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload the image...!.
        /// </summary>
        public static string VLimageuplode {
            get {
                return ResourceManager.GetString("VLimageuplode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The merchant has been introduced to the pricing system. Please confirm and try again later...!.
        /// </summary>
        public static string VLMerchantDoplceted {
            get {
                return ResourceManager.GetString("VLMerchantDoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number has already been entered. Please verify and try again later...!.
        /// </summary>
        public static string VLMerchantMobDoplceted {
            get {
                return ResourceManager.GetString("VLMerchantMobDoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address has already been added. Please check and try again later...!.
        /// </summary>
        public static string VLMerchantNameDoplceted {
            get {
                return ResourceManager.GetString("VLMerchantNameDoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bond number has already been entered. Please check and try again later...!.
        /// </summary>
        public static string VLReceiptNoDoplceted {
            get {
                return ResourceManager.GetString("VLReceiptNoDoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resived Mony.
        /// </summary>
        public static string VlResivedMony {
            get {
                return ResourceManager.GetString("VlResivedMony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validity has already been entered, please confirm and try again later...!.
        /// </summary>
        public static string VLRoleNameDoplceted {
            get {
                return ResourceManager.GetString("VLRoleNameDoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The saving process was completed successfully.
        /// </summary>
        public static string VLSavedSuccessfully {
            get {
                return ResourceManager.GetString("VLSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shipping price address has been entered. Please verify and try again later....!.
        /// </summary>
        public static string VLTitleShippingoplceted {
            get {
                return ResourceManager.GetString("VLTitleShippingoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The company category has already been entered. Please check and try again later...!.
        /// </summary>
        public static string VLTypesCompaniesDoplceted {
            get {
                return ResourceManager.GetString("VLTypesCompaniesDoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message type has already been entered, please check and try again later...!.
        /// </summary>
        public static string VLTypesOfMessageDoplceted {
            get {
                return ResourceManager.GetString("VLTypesOfMessageDoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ordering system has already been entered. Please confirm and try again later....!.
        /// </summary>
        public static string VLTypesOfRequestDoplceted {
            get {
                return ResourceManager.GetString("VLTypesOfRequestDoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delivery system type is already listed, please check and try again later...!.
        /// </summary>
        public static string VLTypeSystemDeliveryDoplceted {
            get {
                return ResourceManager.GetString("VLTypeSystemDeliveryDoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system has already been entered. Please confirm and try again later...!.
        /// </summary>
        public static string VLTypeSystemDoplceted {
            get {
                return ResourceManager.GetString("VLTypeSystemDoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The modification process was completed successfully.
        /// </summary>
        public static string VLUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("VLUpdatedSuccessfully", resourceCulture);
            }
        }
    }
}
