//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yara.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceWebAr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceWebAr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yara.Resource.ResourceWebAr", typeof(ResourceWebAr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة التعامل.
        /// </summary>
        public static string LbActive {
            get {
                return ResourceManager.GetString("LbActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستخدم نشط.
        /// </summary>
        public static string LbActiveUser {
            get {
                return ResourceManager.GetString("LbActiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة وتعديل المناطق.
        /// </summary>
        public static string LBAddArea {
            get {
                return ResourceManager.GetString("LBAddArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة وتعديل أسعار شركات التوصيل للمناطق.
        /// </summary>
        public static string LBAddAreaDeliveryTariffs {
            get {
                return ResourceManager.GetString("LBAddAreaDeliveryTariffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة وتعديل بيانات المدينة.
        /// </summary>
        public static string LBAddCity {
            get {
                return ResourceManager.GetString("LBAddCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة وتعديل أسعار شركات التوصيل للمدن.
        /// </summary>
        public static string LBAddCityDeliveryTariffs {
            get {
                return ResourceManager.GetString("LBAddCityDeliveryTariffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة وتعديل أنظمة العميل مع تعرفة التوصيل.
        /// </summary>
        public static string LBAddClintWitheDeliveryTariffs {
            get {
                return ResourceManager.GetString("LBAddClintWitheDeliveryTariffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة وتعديل العملات.
        /// </summary>
        public static string LBAddCurrenciesExchangeRates {
            get {
                return ResourceManager.GetString("LBAddCurrenciesExchangeRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أضافة وتعديل مسجات العملاء.
        /// </summary>
        public static string LBAddCustomerMessages {
            get {
                return ResourceManager.GetString("LBAddCustomerMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة وتعديل بيانات الشركة.
        /// </summary>
        public static string LbAddEditInformationCompanies {
            get {
                return ResourceManager.GetString("LbAddEditInformationCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافةو تعديل سيرفر التنبيهات .
        /// </summary>
        public static string LBAddEmailAlartSetting {
            get {
                return ResourceManager.GetString("LBAddEmailAlartSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة وتعديل سعر الصرف.
        /// </summary>
        public static string LBAddExchangeRate {
            get {
                return ResourceManager.GetString("LBAddExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة وتعديل التعليمات.
        /// </summary>
        public static string LBAddFAQ {
            get {
                return ResourceManager.GetString("LBAddFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة وصف.
        /// </summary>
        public static string LBAddFAQDescreption {
            get {
                return ResourceManager.GetString("LBAddFAQDescreption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة قائمة.
        /// </summary>
        public static string LBAddFAQList {
            get {
                return ResourceManager.GetString("LBAddFAQList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة وتعديل حالة الطلب.
        /// </summary>
        public static string LBAddOrderCase {
            get {
                return ResourceManager.GetString("LBAddOrderCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة وتعديل اضافة طلب جديد.
        /// </summary>
        public static string LBAddOrderNew {
            get {
                return ResourceManager.GetString("LBAddOrderNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة وتعديل حالة الطلب.
        /// </summary>
        public static string LBAddOrderStatus {
            get {
                return ResourceManager.GetString("LBAddOrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة مدفوعات.
        /// </summary>
        public static string LBAddPaing {
            get {
                return ResourceManager.GetString("LBAddPaing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة ربح.
        /// </summary>
        public static string LBAddProfit {
            get {
                return ResourceManager.GetString("LBAddProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        public static string LbAddres {
            get {
                return ResourceManager.GetString("LbAddres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        public static string LbAddresCompany {
            get {
                return ResourceManager.GetString("LbAddresCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة وتعديل الأدوار.
        /// </summary>
        public static string LBAddRolesName {
            get {
                return ResourceManager.GetString("LBAddRolesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة عنوان شحن.
        /// </summary>
        public static string LBAddShippingAddress {
            get {
                return ResourceManager.GetString("LBAddShippingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة وتعديل الأسعار لأنظمة الشحن.
        /// </summary>
        public static string LBAddShippingPrice {
            get {
                return ResourceManager.GetString("LBAddShippingPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة وتعديل حالة المهمة.
        /// </summary>
        public static string LBAddTaskStatus {
            get {
                return ResourceManager.GetString("LBAddTaskStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة وتعديل حاسبة العملات.
        /// </summary>
        public static string LBAddTransaction {
            get {
                return ResourceManager.GetString("LBAddTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة وتعديل عملية تحويل.
        /// </summary>
        public static string LBAddTransfer {
            get {
                return ResourceManager.GetString("LBAddTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة وتعديل فئات الشركة.
        /// </summary>
        public static string LBAddTypesCompanies {
            get {
                return ResourceManager.GetString("LBAddTypesCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أضافة وتعديل أنواع المسجات .
        /// </summary>
        public static string LBAddTypesOfMessage {
            get {
                return ResourceManager.GetString("LBAddTypesOfMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة وتعديل انواع الطلبات .
        /// </summary>
        public static string LBAddTypesOfRequest {
            get {
                return ResourceManager.GetString("LBAddTypesOfRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة وتعديل الأنظمة.
        /// </summary>
        public static string LBAddTypeSystem {
            get {
                return ResourceManager.GetString("LBAddTypeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة وتعديل نوع نظام التسليم.
        /// </summary>
        public static string LBAddTypeSystemDelivery {
            get {
                return ResourceManager.GetString("LBAddTypeSystemDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكمية.
        /// </summary>
        public static string LbAmount {
            get {
                return ResourceManager.GetString("LbAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bgw.
        /// </summary>
        public static string Lbbgw {
            get {
                return ResourceManager.GetString("Lbbgw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفرع.
        /// </summary>
        public static string Lbbranch {
            get {
                return ResourceManager.GetString("Lbbranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البناء.
        /// </summary>
        public static string LBBuilding {
            get {
                return ResourceManager.GetString("LBBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التجاوز.
        /// </summary>
        public static string Lbbypass {
            get {
                return ResourceManager.GetString("Lbbypass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ايصال القبض.
        /// </summary>
        public static string LbCatchReceiptNo {
            get {
                return ResourceManager.GetString("LbCatchReceiptNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدينة.
        /// </summary>
        public static string LbCity {
            get {
                return ResourceManager.GetString("LbCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعر التوصيل للزبون.
        /// </summary>
        public static string LbClintDelivery {
            get {
                return ResourceManager.GetString("LbClintDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات العميل.
        /// </summary>
        public static string LBClintInformation {
            get {
                return ResourceManager.GetString("LBClintInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعر الشحن للعملاء أكثر من 10.
        /// </summary>
        public static string LbClintPricePerkgAbove10 {
            get {
                return ResourceManager.GetString("LbClintPricePerkgAbove10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعر الشحن للعملاء أقل من 10.
        /// </summary>
        public static string LbClintPricePerkgUnder10 {
            get {
                return ResourceManager.GetString("LbClintPricePerkgUnder10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرمز.
        /// </summary>
        public static string Lbcode {
            get {
                return ResourceManager.GetString("Lbcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرمز.
        /// </summary>
        public static string Lbcodeto {
            get {
                return ResourceManager.GetString("Lbcodeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسعار شركات التوصيل.
        /// </summary>
        public static string LbCompanyDelivery {
            get {
                return ResourceManager.GetString("LbCompanyDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف الشركة.
        /// </summary>
        public static string LbCompanyDescription {
            get {
                return ResourceManager.GetString("LbCompanyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الشركة.
        /// </summary>
        public static string LbCompanyName {
            get {
                return ResourceManager.GetString("LbCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الشركة التجارية.
        /// </summary>
        public static string LbCompanyNamem {
            get {
                return ResourceManager.GetString("LbCompanyNamem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموقع الاكتروني.
        /// </summary>
        public static string LbCompanyURl {
            get {
                return ResourceManager.GetString("LbCompanyURl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المبلغ المحول.
        /// </summary>
        public static string LbConvertedAmount {
            get {
                return ResourceManager.GetString("LbConvertedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعر الشحن للشركة أكثر من 10.
        /// </summary>
        public static string LbCoPricePerkgAbove10 {
            get {
                return ResourceManager.GetString("LbCoPricePerkgAbove10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعر الشحن للشركة أقل من 10.
        /// </summary>
        public static string LbCoPricePerkgUnder10 {
            get {
                return ResourceManager.GetString("LbCoPricePerkgUnder10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعر الكلفة.
        /// </summary>
        public static string LbCostPrice {
            get {
                return ResourceManager.GetString("LbCostPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العملة.
        /// </summary>
        public static string LbCountry {
            get {
                return ResourceManager.GetString("LbCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعر الصرف إلى.
        /// </summary>
        public static string LbCountryto {
            get {
                return ResourceManager.GetString("LbCountryto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ائتمان.
        /// </summary>
        public static string Lbcredit {
            get {
                return ResourceManager.GetString("Lbcredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العملة.
        /// </summary>
        public static string LbCurrency {
            get {
                return ResourceManager.GetString("LbCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة.
        /// </summary>
        public static string lbCurrentState {
            get {
                return ResourceManager.GetString("lbCurrentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أقرب نقطة علام.
        /// </summary>
        public static string Lbcust_landmark {
            get {
                return ResourceManager.GetString("Lbcust_landmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الهاتف الاول.
        /// </summary>
        public static string Lbcust_mob {
            get {
                return ResourceManager.GetString("Lbcust_mob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الهاتف الثاني.
        /// </summary>
        public static string Lbcust_mob2 {
            get {
                return ResourceManager.GetString("Lbcust_mob2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الزبون.
        /// </summary>
        public static string Lbcust_name {
            get {
                return ResourceManager.GetString("Lbcust_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف الشخصي.
        /// </summary>
        public static string Lbcust_profile {
            get {
                return ResourceManager.GetString("Lbcust_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة القديمة.
        /// </summary>
        public static string Lbcust_status {
            get {
                return ResourceManager.GetString("Lbcust_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العميل .
        /// </summary>
        public static string LBCustomeronorder {
            get {
                return ResourceManager.GetString("LBCustomeronorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العملاء.
        /// </summary>
        public static string LBCustomers {
            get {
                return ResourceManager.GetString("LBCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخال بيانات.
        /// </summary>
        public static string LbDataEntry {
            get {
                return ResourceManager.GetString("LbDataEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وقت وتاريخ الدخول.
        /// </summary>
        public static string LbDateTimeEntry {
            get {
                return ResourceManager.GetString("LbDateTimeEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رسوم التوصيل.
        /// </summary>
        public static string Lbdelivery_charges {
            get {
                return ResourceManager.GetString("Lbdelivery_charges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LBDeliveryAddress {
            get {
                return ResourceManager.GetString("LBDeliveryAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المنطقة.
        /// </summary>
        public static string LbDescription {
            get {
                return ResourceManager.GetString("LbDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف.
        /// </summary>
        public static string LbDescription1 {
            get {
                return ResourceManager.GetString("LbDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدينة.
        /// </summary>
        public static string Lbdescriptioncity {
            get {
                return ResourceManager.GetString("Lbdescriptioncity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف العميل.
        /// </summary>
        public static string LbDescriptionClint {
            get {
                return ResourceManager.GetString("LbDescriptionClint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف الطلب.
        /// </summary>
        public static string LbDescriptionOrder {
            get {
                return ResourceManager.GetString("LbDescriptionOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف حالة الطلب.
        /// </summary>
        public static string LbdescriptionOrderStuse {
            get {
                return ResourceManager.GetString("LbdescriptionOrderStuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حجم الصورة 150*150.
        /// </summary>
        public static string LBEmageSise {
            get {
                return ResourceManager.GetString("LBEmageSise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني.
        /// </summary>
        public static string LbEmailCompany {
            get {
                return ResourceManager.GetString("LbEmailCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصرف.
        /// </summary>
        public static string LbExchangeAmount {
            get {
                return ResourceManager.GetString("LbExchangeAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعر الصرف.
        /// </summary>
        public static string LbExchangedPrice {
            get {
                return ResourceManager.GetString("LbExchangedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعر الصرف.
        /// </summary>
        public static string LbExchangeRate {
            get {
                return ResourceManager.GetString("LbExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التعليمات.
        /// </summary>
        public static string LbFAQ {
            get {
                return ResourceManager.GetString("LbFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف وصف التعليمة.
        /// </summary>
        public static string LbFAQDescreption {
            get {
                return ResourceManager.GetString("LbFAQDescreption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة السؤال.
        /// </summary>
        public static string LbFAQList {
            get {
                return ResourceManager.GetString("LbFAQList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fb.
        /// </summary>
        public static string Lbfbid {
            get {
                return ResourceManager.GetString("Lbfbid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطابق.
        /// </summary>
        public static string LBFloor {
            get {
                return ResourceManager.GetString("LBFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حزمة كاملة.
        /// </summary>
        public static string Lbfull_package {
            get {
                return ResourceManager.GetString("Lbfull_package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاعدادات العامة.
        /// </summary>
        public static string LBGeneralSettings {
            get {
                return ResourceManager.GetString("LBGeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رابط.
        /// </summary>
        public static string Lbgisurl {
            get {
                return ResourceManager.GetString("Lbgisurl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرمز.
        /// </summary>
        public static string Lbhexcode {
            get {
                return ResourceManager.GetString("Lbhexcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مخفي.
        /// </summary>
        public static string Lbhidden {
            get {
                return ResourceManager.GetString("Lbhidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرمز الست عشري.
        /// </summary>
        public static string LBhxcode {
            get {
                return ResourceManager.GetString("LBhxcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المعرف.
        /// </summary>
        public static string LbId {
            get {
                return ResourceManager.GetString("LbId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف التعليمة.
        /// </summary>
        public static string LbIdFAQ {
            get {
                return ResourceManager.GetString("LbIdFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف وصف السؤال.
        /// </summary>
        public static string LbIdFAQDescreption {
            get {
                return ResourceManager.GetString("LbIdFAQDescreption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معرف قائمة السؤال.
        /// </summary>
        public static string LbIdFAQList {
            get {
                return ResourceManager.GetString("LbIdFAQList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المعلومات.
        /// </summary>
        public static string LbInformaition {
            get {
                return ResourceManager.GetString("LbInformaition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات العميل.
        /// </summary>
        public static string LbInformaitioncl {
            get {
                return ResourceManager.GetString("LbInformaitioncl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات الشركة.
        /// </summary>
        public static string LbInformaitionco {
            get {
                return ResourceManager.GetString("LbInformaitionco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات الشركة.
        /// </summary>
        public static string LbInformationCompany {
            get {
                return ResourceManager.GetString("LbInformationCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الاضافة.
        /// </summary>
        public static string Lbinsert_dt {
            get {
                return ResourceManager.GetString("Lbinsert_dt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنوب.
        /// </summary>
        public static string LbIsNorth {
            get {
                return ResourceManager.GetString("LbIsNorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدفع.
        /// </summary>
        public static string lbIsPaid {
            get {
                return ResourceManager.GetString("lbIsPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عام.
        /// </summary>
        public static string LbisPublic {
            get {
                return ResourceManager.GetString("LbisPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خط العرض.
        /// </summary>
        public static string Lblat {
            get {
                return ResourceManager.GetString("Lblat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المنطقة.
        /// </summary>
        public static string LBLbAreaName {
            get {
                return ResourceManager.GetString("LBLbAreaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصلاحيات.
        /// </summary>
        public static string LBLbRoles {
            get {
                return ResourceManager.GetString("LBLbRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة السؤال.
        /// </summary>
        public static string LbListFAQ {
            get {
                return ResourceManager.GetString("LbListFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خط الطول.
        /// </summary>
        public static string Lblon {
            get {
                return ResourceManager.GetString("Lblon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بريد الارسال.
        /// </summary>
        public static string lbMailSender {
            get {
                return ResourceManager.GetString("lbMailSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف.
        /// </summary>
        public static string Lbmerchant_mob {
            get {
                return ResourceManager.GetString("Lbmerchant_mob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم التاجر.
        /// </summary>
        public static string LbMerchant_name {
            get {
                return ResourceManager.GetString("LbMerchant_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات التاجر.
        /// </summary>
        public static string LBMerchantInformation {
            get {
                return ResourceManager.GetString("LBMerchantInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التجار.
        /// </summary>
        public static string LBMerchants {
            get {
                return ResourceManager.GetString("LBMerchants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رسالة العميل .
        /// </summary>
        public static string LbMessageDescription {
            get {
                return ResourceManager.GetString("LbMessageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في اسم المستخدم أو كلمة المرور .....!.
        /// </summary>
        public static string lbMsgErrorLogin {
            get {
                return ResourceManager.GetString("lbMsgErrorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ لم يتم حفظ كلمة المرور الجديدة...!.
        /// </summary>
        public static string lbMsgNotSavedChangePassword {
            get {
                return ResourceManager.GetString("lbMsgNotSavedChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حفظ كلمة المرور الجديدة بنجاح.
        /// </summary>
        public static string lbMsgSavedChangePassword {
            get {
                return ResourceManager.GetString("lbMsgSavedChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المناطق.
        /// </summary>
        public static string LBMyArea {
            get {
                return ResourceManager.GetString("LBMyArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسعار شركات التوصيل للمناطق.
        /// </summary>
        public static string LBMyAreaDeliveryTariffs {
            get {
                return ResourceManager.GetString("LBMyAreaDeliveryTariffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات المدن.
        /// </summary>
        public static string LBMyCity {
            get {
                return ResourceManager.GetString("LBMyCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسعار شركات التوصيل للمدن.
        /// </summary>
        public static string LBMyCityDeliveryTariffs {
            get {
                return ResourceManager.GetString("LBMyCityDeliveryTariffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العميل مع رسوم التوصيل.
        /// </summary>
        public static string LBMyClintWitheDeliveryTariffs {
            get {
                return ResourceManager.GetString("LBMyClintWitheDeliveryTariffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العملات.
        /// </summary>
        public static string LBMyCurrenciesExchangeRates {
            get {
                return ResourceManager.GetString("LBMyCurrenciesExchangeRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات العملاء الفردية.
        /// </summary>
        public static string LBMyCustomer {
            get {
                return ResourceManager.GetString("LBMyCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رسائل العملاء .
        /// </summary>
        public static string LBMyCustomerMessages {
            get {
                return ResourceManager.GetString("LBMyCustomerMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أعدادات بريدي التنبيهات.
        /// </summary>
        public static string LBMyEmailAlartSettingAr {
            get {
                return ResourceManager.GetString("LBMyEmailAlartSettingAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعر الصرف.
        /// </summary>
        public static string LBMyExchangeRate {
            get {
                return ResourceManager.GetString("LBMyExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التعليمات.
        /// </summary>
        public static string LbMyFAQ {
            get {
                return ResourceManager.GetString("LbMyFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف التعليمات .
        /// </summary>
        public static string LbMyFAQDescreption {
            get {
                return ResourceManager.GetString("LbMyFAQDescreption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة السؤال.
        /// </summary>
        public static string LbMyFAQList {
            get {
                return ResourceManager.GetString("LbMyFAQList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات الشركات.
        /// </summary>
        public static string LBMYInformationCompanies {
            get {
                return ResourceManager.GetString("LBMYInformationCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات التجار.
        /// </summary>
        public static string LBMyMerchant {
            get {
                return ResourceManager.GetString("LBMyMerchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطلب.
        /// </summary>
        public static string LBMyOrder {
            get {
                return ResourceManager.GetString("LBMyOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالات الطلب.
        /// </summary>
        public static string LBMyOrderCase {
            get {
                return ResourceManager.GetString("LBMyOrderCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلب جديد.
        /// </summary>
        public static string LBMyOrderNew {
            get {
                return ResourceManager.GetString("LBMyOrderNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة الطلب.
        /// </summary>
        public static string LBMyOrderStatus {
            get {
                return ResourceManager.GetString("LBMyOrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأدوار.
        /// </summary>
        public static string LBMyRolesName {
            get {
                return ResourceManager.GetString("LBMyRolesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عناوين الشحن.
        /// </summary>
        public static string LBMyShippingAddress {
            get {
                return ResourceManager.GetString("LBMyShippingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسعار أنظمة الشحن.
        /// </summary>
        public static string LBMyShippingPrice {
            get {
                return ResourceManager.GetString("LBMyShippingPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة المهمة.
        /// </summary>
        public static string LBMyTaskStatus {
            get {
                return ResourceManager.GetString("LBMyTaskStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حاسبة العملة.
        /// </summary>
        public static string LBMyTransaction {
            get {
                return ResourceManager.GetString("LBMyTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التحويلات.
        /// </summary>
        public static string LBMyTransfers {
            get {
                return ResourceManager.GetString("LBMyTransfers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فئات الشركات.
        /// </summary>
        public static string LBMyTypesCompanies {
            get {
                return ResourceManager.GetString("LBMyTypesCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنواع المسجات .
        /// </summary>
        public static string LBMyTypesOfMessage {
            get {
                return ResourceManager.GetString("LBMyTypesOfMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنواع الطلبات.
        /// </summary>
        public static string LBMyTypesOfRequest {
            get {
                return ResourceManager.GetString("LBMyTypesOfRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأنظمة.
        /// </summary>
        public static string LBMyTypeSystem {
            get {
                return ResourceManager.GetString("LBMyTypeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع نظام التسليم.
        /// </summary>
        public static string LBMyTypeSystemDelivery {
            get {
                return ResourceManager.GetString("LBMyTypeSystemDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LbName {
            get {
                return ResourceManager.GetString("LbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الدور.
        /// </summary>
        public static string LbNameRols {
            get {
                return ResourceManager.GetString("LbNameRols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللقب.
        /// </summary>
        public static string LbNikeNAme {
            get {
                return ResourceManager.GetString("LbNikeNAme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم شركة التاجر.
        /// </summary>
        public static string LbNikeNAmeM {
            get {
                return ResourceManager.GetString("LbNikeNAmeM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الطبيعي.
        /// </summary>
        public static string LbNormalizedName {
            get {
                return ResourceManager.GetString("LbNormalizedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات.
        /// </summary>
        public static string Lbnotes {
            get {
                return ResourceManager.GetString("Lbnotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ أثناء الحفظ. يرجى التحقق والمحاولة مرة أخرى لاحقا...!.
        /// </summary>
        public static string lbNotSaved {
            get {
                return ResourceManager.GetString("lbNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم حفظ عملية الصلاحية، يرجى التحقق والمحاولة مرة أخرى لاحقًا.
        /// </summary>
        public static string lbNotSavedMsgRole {
            get {
                return ResourceManager.GetString("lbNotSavedMsgRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم حفظ عملية الصلاحية، يرجى التحقق والمحاولة مرة أخرى لاحقًا.
        /// </summary>
        public static string lbNotSavedMsgUser {
            get {
                return ResourceManager.GetString("lbNotSavedMsgUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم حفظ عملية الصلاحية، يرجى التحقق والمحاولة مرة أخرى لاحقًا.
        /// </summary>
        public static string lbNotSavedMsgUserRole {
            get {
                return ResourceManager.GetString("lbNotSavedMsgUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ أثناء عملية التحرير. يرجى التحقق والمحاولة مرة أخرى لاحقا..!.
        /// </summary>
        public static string lbNotUpdate {
            get {
                return ResourceManager.GetString("lbNotUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ أثناء عملية التحرير. يرجى التحقق والمحاولة مرة أخرى لاحقا..!.
        /// </summary>
        public static string lbNotUpdateMsgRole {
            get {
                return ResourceManager.GetString("lbNotUpdateMsgRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ أثناء عملية التحرير. يرجى التحقق والمحاولة مرة أخرى لاحقا..!.
        /// </summary>
        public static string lbNotUpdateMsgUser {
            get {
                return ResourceManager.GetString("lbNotUpdateMsgUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ أثناء عملية التحرير. يرجى التحقق والمحاولة مرة أخرى لاحقا..!.
        /// </summary>
        public static string lbNotUpdateMsgUserRole {
            get {
                return ResourceManager.GetString("lbNotUpdateMsgUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظة.
        /// </summary>
        public static string LbNouts {
            get {
                return ResourceManager.GetString("LbNouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات الطلب .
        /// </summary>
        public static string LbNoutsOrder {
            get {
                return ResourceManager.GetString("LbNoutsOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المكتب.
        /// </summary>
        public static string LbOffice {
            get {
                return ResourceManager.GetString("LbOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصورة القديمة.
        /// </summary>
        public static string lbOldeAndUserGide {
            get {
                return ResourceManager.GetString("lbOldeAndUserGide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العمليات.
        /// </summary>
        public static string LbOpration {
            get {
                return ResourceManager.GetString("LbOpration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطلبات.
        /// </summary>
        public static string Lborder {
            get {
                return ResourceManager.GetString("Lborder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة.
        /// </summary>
        public static string LbOrderCase {
            get {
                return ResourceManager.GetString("LbOrderCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالات الطلب.
        /// </summary>
        public static string LborderCases {
            get {
                return ResourceManager.GetString("LborderCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الطلب.
        /// </summary>
        public static string LbOrderDate {
            get {
                return ResourceManager.GetString("LbOrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات الطلب.
        /// </summary>
        public static string LBOrderInformation {
            get {
                return ResourceManager.GetString("LBOrderInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظام الطلبيات.
        /// </summary>
        public static string LBOrdersSystem {
            get {
                return ResourceManager.GetString("LBOrdersSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة الطلب.
        /// </summary>
        public static string LBOrderStatus {
            get {
                return ResourceManager.GetString("LBOrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ضواحي المدينة.
        /// </summary>
        public static string Lboutskirts {
            get {
                return ResourceManager.GetString("Lboutskirts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات الدفع.
        /// </summary>
        public static string LBPaidingInformations {
            get {
                return ResourceManager.GetString("LBPaidingInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدفوعات.
        /// </summary>
        public static string LBPaidings {
            get {
                return ResourceManager.GetString("LBPaidings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        public static string lbPasswordEmail {
            get {
                return ResourceManager.GetString("lbPasswordEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف.
        /// </summary>
        public static string LbPhoneCompany {
            get {
                return ResourceManager.GetString("LbPhoneCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف 2.
        /// </summary>
        public static string LbPhoneCompanySecand {
            get {
                return ResourceManager.GetString("LbPhoneCompanySecand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصورة.
        /// </summary>
        public static string LbPhoto {
            get {
                return ResourceManager.GetString("LbPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المنفذ.
        /// </summary>
        public static string lbPortServer {
            get {
                return ResourceManager.GetString("lbPortServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السعر.
        /// </summary>
        public static string LbPrice {
            get {
                return ResourceManager.GetString("LbPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظام الاسعار.
        /// </summary>
        public static string LBPricingSystem {
            get {
                return ResourceManager.GetString("LBPricingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف الشخصي.
        /// </summary>
        public static string LBProfile {
            get {
                return ResourceManager.GetString("LBProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كمية الربح.
        /// </summary>
        public static string LbProfitAmount {
            get {
                return ResourceManager.GetString("LbProfitAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات الأرباح.
        /// </summary>
        public static string LBProfitsInformations {
            get {
                return ResourceManager.GetString("LBProfitsInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السؤال.
        /// </summary>
        public static string LbQuastion {
            get {
                return ResourceManager.GetString("LbQuastion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف السؤال.
        /// </summary>
        public static string LbQuastionDesc {
            get {
                return ResourceManager.GetString("LbQuastionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة السؤال.
        /// </summary>
        public static string LbQuastionList {
            get {
                return ResourceManager.GetString("LbQuastionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعر الصرف.
        /// </summary>
        public static string LbRate {
            get {
                return ResourceManager.GetString("LbRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الاستلام.
        /// </summary>
        public static string LBreceipt_dt {
            get {
                return ResourceManager.GetString("LBreceipt_dt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الإيصال.
        /// </summary>
        public static string LBreceipt_no {
            get {
                return ResourceManager.GetString("LBreceipt_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيان الاستلام.
        /// </summary>
        public static string LbReceiptStatment {
            get {
                return ResourceManager.GetString("LbReceiptStatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المبلغ المستلم.
        /// </summary>
        public static string LbResivedMony {
            get {
                return ResourceManager.GetString("LbResivedMony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدور.
        /// </summary>
        public static string Lbrole {
            get {
                return ResourceManager.GetString("Lbrole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الدور.
        /// </summary>
        public static string LbRolesName {
            get {
                return ResourceManager.GetString("LbRolesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string lbSave {
            get {
                return ResourceManager.GetString("lbSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string lbSaveMsgRole {
            get {
                return ResourceManager.GetString("lbSaveMsgRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القطاع.
        /// </summary>
        public static string LbSector {
            get {
                return ResourceManager.GetString("LbSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رسوم الخدمات.
        /// </summary>
        public static string LBservice_charges {
            get {
                return ResourceManager.GetString("LBservice_charges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عناوين الشحن.
        /// </summary>
        public static string LBShippingAddress {
            get {
                return ResourceManager.GetString("LBShippingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات عناوين الشحن.
        /// </summary>
        public static string LBShippingAddressInfo {
            get {
                return ResourceManager.GetString("LBShippingAddressInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقع عناوين الشحن.
        /// </summary>
        public static string LBShippingAddressLocation {
            get {
                return ResourceManager.GetString("LBShippingAddressLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التنبيه عبر الرسائل القصيرة.
        /// </summary>
        public static string Lbsms_alert {
            get {
                return ResourceManager.GetString("Lbsms_alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سيرفر الارسال.
        /// </summary>
        public static string lbSmtpServer {
            get {
                return ResourceManager.GetString("lbSmtpServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التصنيف.
        /// </summary>
        public static string Lbsorting {
            get {
                return ResourceManager.GetString("Lbsorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مساحة.
        /// </summary>
        public static string LbSpec {
            get {
                return ResourceManager.GetString("LbSpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صلاحية SSL.
        /// </summary>
        public static string lbSsl_validity {
            get {
                return ResourceManager.GetString("lbSsl_validity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشارع.
        /// </summary>
        public static string LBStreet {
            get {
                return ResourceManager.GetString("LBStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة المهمة.
        /// </summary>
        public static string LbTaskStatus {
            get {
                return ResourceManager.GetString("LbTaskStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        public static string LbTitle {
            get {
                return ResourceManager.GetString("LbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان الشحن.
        /// </summary>
        public static string LbTitleShipping {
            get {
                return ResourceManager.GetString("LbTitleShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المبلغ.
        /// </summary>
        public static string LbTransferAmount {
            get {
                return ResourceManager.GetString("LbTransferAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات التحويل.
        /// </summary>
        public static string LBTransferInformations {
            get {
                return ResourceManager.GetString("LBTransferInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفئة.
        /// </summary>
        public static string LbTypesCompanies {
            get {
                return ResourceManager.GetString("LbTypesCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنواع الشركات التجارية.
        /// </summary>
        public static string LbTypesCompaniesM {
            get {
                return ResourceManager.GetString("LbTypesCompaniesM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المسج.
        /// </summary>
        public static string LbTypesOfMessage {
            get {
                return ResourceManager.GetString("LbTypesOfMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النوع .
        /// </summary>
        public static string LbTypesOfRequest {
            get {
                return ResourceManager.GetString("LbTypesOfRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النظام.
        /// </summary>
        public static string LbTypeSystem {
            get {
                return ResourceManager.GetString("LbTypeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحديث.
        /// </summary>
        public static string lbUpdate {
            get {
                return ResourceManager.GetString("lbUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحديث.
        /// </summary>
        public static string lbUpdateMsgRole {
            get {
                return ResourceManager.GetString("lbUpdateMsgRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رفع.
        /// </summary>
        public static string LBUpload_image {
            get {
                return ResourceManager.GetString("LBUpload_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستخدم نظام التوصيل.
        /// </summary>
        public static string LbUS_delivery {
            get {
                return ResourceManager.GetString("LbUS_delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصورة.
        /// </summary>
        public static string LbUserEmage {
            get {
                return ResourceManager.GetString("LbUserEmage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني للمستخدم.
        /// </summary>
        public static string LbUserEmail {
            get {
                return ResourceManager.GetString("LbUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        public static string LbUserName {
            get {
                return ResourceManager.GetString("LbUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الهاتف.
        /// </summary>
        public static string LbUserPhone {
            get {
                return ResourceManager.GetString("LbUserPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        public static string Lbuserpwd {
            get {
                return ResourceManager.GetString("Lbuserpwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات المستخدمين.
        /// </summary>
        public static string LBUsersInformationEn {
            get {
                return ResourceManager.GetString("LBUsersInformationEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوزن.
        /// </summary>
        public static string LbWeight {
            get {
                return ResourceManager.GetString("LbWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مع تسليم.
        /// </summary>
        public static string Lbwith_delivery {
            get {
                return ResourceManager.GetString("Lbwith_delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحي السكني.
        /// </summary>
        public static string LbZone {
            get {
                return ResourceManager.GetString("LbZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرح صلاحية الشحن.
        /// </summary>
        public static string LTitleShipping {
            get {
                return ResourceManager.GetString("LTitleShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت بالفعل إضافة التسعير إلى المنطقة. يرجى التحقق والمحاولة مرة أخرى لاحقا...!.
        /// </summary>
        public static string VLAreadoplceted {
            get {
                return ResourceManager.GetString("VLAreadoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إدخال سعر التسليم لهذه المدينة. يرجى التحقق والمحاولة مرة أخرى لاحقا...!.
        /// </summary>
        public static string VLCitydoplceted {
            get {
                return ResourceManager.GetString("VLCitydoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد تم بالفعل إدخال الشركة. يرجى التحقق والمحاولة مرة أخرى لاحقا....!.
        /// </summary>
        public static string VLCompanyNameDoplceted {
            get {
                return ResourceManager.GetString("VLCompanyNameDoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد تم بالفعل إدخال البلاد. يرجى التحقق والمحاولة مرة أخرى لاحقا...!.
        /// </summary>
        public static string VLCountryDoplceted {
            get {
                return ResourceManager.GetString("VLCountryDoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد تم بالفعل إدخال هاتف العميل. يرجى التأكيد والمحاولة مرة أخرى لاحقاً...!.
        /// </summary>
        public static string VLCustMob2doplceted {
            get {
                return ResourceManager.GetString("VLCustMob2doplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد تم بالفعل إدخال هاتف العميل. يرجى التأكيد والمحاولة مرة أخرى لاحقاً...!.
        /// </summary>
        public static string VLCustMobdoplceted {
            get {
                return ResourceManager.GetString("VLCustMobdoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد تم بالفعل إدخال اسم العميل. يرجى التحقق والمحاولة مرة أخرى لاحقا....!.
        /// </summary>
        public static string VLCustNamedoplceted {
            get {
                return ResourceManager.GetString("VLCustNamedoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعريف العميل بنظام التسعير. يرجى التأكيد والمحاولة مرة أخرى لاحقاً...!.
        /// </summary>
        public static string VLCustomerDoplceted {
            get {
                return ResourceManager.GetString("VLCustomerDoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يكتمل الحذف. كان هناك خطأ.
        /// </summary>
        public static string VLDeleteError {
            get {
                return ResourceManager.GetString("VLDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية الحذف بنجاح.
        /// </summary>
        public static string VLDeletesuccessful {
            get {
                return ResourceManager.GetString("VLDeletesuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية الحذف بنجاح.
        /// </summary>
        public static string VLdELETESuccessfully {
            get {
                return ResourceManager.GetString("VLdELETESuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد تم بالفعل إدخال المنطقة. يرجى التحقق والمحاولة مرة أخرى لاحقا...!.
        /// </summary>
        public static string VLDescriptionareadoplceted {
            get {
                return ResourceManager.GetString("VLDescriptionareadoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم بالفعل إدخال وصف الاتصال بنظام التعريفة. يرجى التحقق والمحاولة مرة أخرى لاحقا...!.
        /// </summary>
        public static string VLDescriptionClintDoplceted {
            get {
                return ResourceManager.GetString("VLDescriptionClintDoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد تم بالفعل دخول المدينة. يرجى التحقق والمحاولة مرة أخرى لاحقا....!.
        /// </summary>
        public static string VLDescriptionDoplceted {
            get {
                return ResourceManager.GetString("VLDescriptionDoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إدخال حالة الطلب. يرجى التأكيد والمحاولة مرة أخرى لاحقا....!.
        /// </summary>
        public static string VLDescriptiondplceted {
            get {
                return ResourceManager.GetString("VLDescriptiondplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد تم بالفعل إدخال وصف الطلب. يرجى التأكيد والمحاولة مرة أخرى لاحقاً...!.
        /// </summary>
        public static string VLDescriptionOrderDoplceted {
            get {
                return ResourceManager.GetString("VLDescriptionOrderDoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني أو اسم المستخدم موجود بالفعل...!.
        /// </summary>
        public static string VLEmailOreUserOrPaswo {
            get {
                return ResourceManager.GetString("VLEmailOreUserOrPaswo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ بالحذف...!.
        /// </summary>
        public static string VLErrorDeleteData {
            get {
                return ResourceManager.GetString("VLErrorDeleteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ أثناء عملية الحفظ....!.
        /// </summary>
        public static string VLErrorSave {
            get {
                return ResourceManager.GetString("VLErrorSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في عملية التحرير....!.
        /// </summary>
        public static string VLErrorUpdate {
            get {
                return ResourceManager.GetString("VLErrorUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إدخال العملة بالفعل. يرجى التحقق والمحاولة مرة أخرى لاحقا...!.
        /// </summary>
        public static string VLExchangeRateDoplceted {
            get {
                return ResourceManager.GetString("VLExchangeRateDoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إدخال السؤال مسبقا.. يرجى التأكد والمحاولة لاحقا..!.
        /// </summary>
        public static string VLFAQDoplceted {
            get {
                return ResourceManager.GetString("VLFAQDoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إدخال الرمز بالفعل، يرجى التحقق والمحاولة مرة أخرى لاحقًا...!.
        /// </summary>
        public static string VLHxcodedoplceted {
            get {
                return ResourceManager.GetString("VLHxcodedoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك ارفع الصورة...!.
        /// </summary>
        public static string VLimageuplode {
            get {
                return ResourceManager.GetString("VLimageuplode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تعريف التاجر بنظام التسعير. يرجى التأكيد والمحاولة مرة أخرى لاحقاً...!.
        /// </summary>
        public static string VLMerchantDoplceted {
            get {
                return ResourceManager.GetString("VLMerchantDoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد تم إدخال رقم الهاتف بالفعل. يرجى التحقق والمحاولة مرة أخرى لاحقا...!.
        /// </summary>
        public static string VLMerchantMobDoplceted {
            get {
                return ResourceManager.GetString("VLMerchantMobDoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت إضافة عنوان البريد الإلكتروني بالفعل. يرجى التحقق والمحاولة مرة أخرى لاحقا...!.
        /// </summary>
        public static string VLMerchantNameDoplceted {
            get {
                return ResourceManager.GetString("VLMerchantNameDoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد تم إدخال الصلاحية بالفعل، يرجى التأكيد والمحاولة مرة أخرى لاحقاً...!.
        /// </summary>
        public static string VLRoleNameDoplceted {
            get {
                return ResourceManager.GetString("VLRoleNameDoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية الحفظ بنجاح.
        /// </summary>
        public static string VLSavedSuccessfully {
            get {
                return ResourceManager.GetString("VLSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إدخال عنوان سعر الشحن. يرجى التحقق والمحاولة مرة أخرى لاحقا....!.
        /// </summary>
        public static string VLTitleShippingoplceted {
            get {
                return ResourceManager.GetString("VLTitleShippingoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد تم بالفعل إدخال فئة الشركة. يرجى التحقق والمحاولة مرة أخرى لاحقا...!.
        /// </summary>
        public static string VLTypesCompaniesDoplceted {
            get {
                return ResourceManager.GetString("VLTypesCompaniesDoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إدخال نوع الرسالة مسبقا يرجى التأكد وإعادة المحاولة لاحقا ....
        /// </summary>
        public static string VLTypesOfMessageDoplceted {
            get {
                return ResourceManager.GetString("VLTypesOfMessageDoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم ادخال نوع الطلب مسبقا يرجى التأكد وإعادة المحاولة لاحقا ..!.
        /// </summary>
        public static string VLTypesOfRequestDoplceted {
            get {
                return ResourceManager.GetString("VLTypesOfRequestDoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع نظام التسليم مدرج بالفعل، يرجى التحقق والمحاولة مرة أخرى لاحقًا...!.
        /// </summary>
        public static string VLTypeSystemDeliveryDoplceted {
            get {
                return ResourceManager.GetString("VLTypeSystemDeliveryDoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد تم بالفعل إدخال النظام. يرجى التأكيد والمحاولة مرة أخرى لاحقاً...!.
        /// </summary>
        public static string VLTypeSystemDoplceted {
            get {
                return ResourceManager.GetString("VLTypeSystemDoplceted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت عملية التعديل بنجاح.
        /// </summary>
        public static string VLUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("VLUpdatedSuccessfully", resourceCulture);
            }
        }
    }
}
